#!/usr/bin/env node
// Image pipeline. Reads works from the content repository and produces:
// (<year> is the year of the work's date; the content repository has no year folders, see scripts/lib/content.mjs)
//   content/works/<year>/<slug>-<id>.yaml              copy of the metadata for the site build (commit)
//   public/works/<year>/<slug>-<id>/<width>.{avif,webp,jpg}, info.json   web images (commit)
//   public/works/<year>/<slug>-<id>/mockup-<scene>-<width>.*              the work in an interior, only with `mockups: true` (commit);
//                                                                        from the bare sheet when the master shows surroundings
//   public/works/<year>/<slug>-<id>/detail-<name>-<width>.*               detail photos of the work (commit)
//   public/works/<year>/<slug>-<id>/og.jpg                                share image (og:image): the whole work on paper, 3:2 (commit)
//   public/photos/<name>/<width>.{avif,webp,jpg}, info.json                other photos of the site (commit)
//   content/collections/<slug>.yaml                                      copy of a collection description (commit)
//   public/collections/<slug>/<width>.{avif,webp,jpg}, info.json          cover photo of a collection (commit)
//   public/og/collections/<slug>.jpg                                     share image (og:image) of a collection: its cover
//                                                                        cropped to 3:2 around `focus`, as on the page (commit)
//   <contentDir>/export/instagram/<year>/<key>-clean.jpg          Instagram, the original on paper, 4:5
//   <contentDir>/export/instagram/<year>/<key>-detail-<name>.jpg  Instagram, a detail photo cropped to 4:5 (never mockups)
//   (Instagram exports only for works with `instagram: true`; otherwise they are removed)
//
// Copies for the public site repository contain only public fields: private_note never leaves the content repository.
//   <contentDir>/export/fler/<year>/<key>.jpg                     Fler, the original with the author's name as watermark
//   <contentDir>/export/fler/<year>/<key>-mockup-<scene>.jpg      Fler, the mockups with the same watermark
//   (Fler exports only for works on sale: available or reserved; otherwise they are removed)
//
// Usage:  npm run images             (only works whose outputs are missing or older than the master)
//         npm run images -- --force  (regenerate everything)
//         npm run images -- --prepare-only  (only skeletons, ids and checks of the content; no images, site or
//                                            exports; used by the automation on branches of the content repository)
//         npm run images -- <slug>   (a single work; skips pruning)
// Content location: CONTENT_DIR (locally from .env, see package.json), or images.contentDir in site.config.yaml.

import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import sharp from 'sharp';
import YAML from 'yaml';
import { PUBLIC_COLLECTION_FIELDS, coverSource, prepareCollections, validateCollectionCovers } from './lib/collections.mjs';
import { PUBLIC_YEAR_FIELDS, prepareYears } from './lib/years.mjs';
import { PUBLIC_HOME_FIELDS, prepareHome } from './lib/home.mjs';
import { coverProblems, coverShareSource } from './lib/covers.mjs';
import { prepareContent } from './lib/content.mjs';
import { demoProblems } from './lib/demo.mjs';
import { loadScenes, pickScenes, renderMockup } from './lib/mockups.mjs';
import { focusCrop, photoFocus, preparePhotos } from './lib/photos.mjs';
import { boxRegion, parseSheetXmp } from './lib/sheet-box.mjs';
import { formatSummary } from './lib/summary.mjs';
import {
  PUBLIC_WORK_FIELDS, expectedExports, exportPattern, isOnSale, wantsInstagram, wantsMockups, planExportPrune, planPrune, publicFields, validateWorks, workKey,
} from './lib/works.mjs';

/** Bump when the output format changes, so every work is regenerated once. */
const PIPELINE_VERSION = 6;

const siteRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const exists = (p) => fs.access(p).then(() => true, () => false);
const readJson = (p) => fs.readFile(p, 'utf8').then(JSON.parse, () => null);
const sha1 = (...parts) => {
  const h = createHash('sha1');
  for (const p of parts) h.update(typeof p === 'string' ? p : Buffer.from(p));
  return h.digest('hex').slice(0, 16);
};
const esc = (s) => String(s).replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);

const SYNC_HEADER = '# Generated by `npm run images` from the content repository. Do not edit here, changes will be overwritten.\n';

/** Text of a public metadata copy: only the given fields, no comments (they could hold private notes). */
const publicCopy = (data, fields) => SYNC_HEADER + YAML.stringify(publicFields(data, fields));

/** Writes `text` only when it differs, to keep git diffs clean. */
async function writeIfChanged(file, text) {
  if ((await fs.readFile(file, 'utf8').catch(() => null)) === text) return;
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, text);
}

// Load the master once: convert to sRGB and apply EXIF rotation. Metadata (EXIF, GPS) is not copied to outputs.
// `sheet`: where the bare paper lies when the master also shows its surroundings (XMP written by
// `npm run straighten`, see scripts/lib/sheet-box.mjs); null for a master that is the sheet itself.
async function loadMaster(input) {
  const buf = await sharp(input).rotate().toColorspace('srgb').toBuffer();
  const meta = await sharp(buf).metadata();
  const sheet = parseSheetXmp((await sharp(input).metadata()).xmp);
  return { buf, width: meta.width, height: meta.height, sheet };
}

/** The master for the mockups: cropped to the bare sheet, a framed work never shows the floor around it. */
const mockupSource = (m) => (m.sheet ? sharp(m.buf).extract(boxRegion(m.sheet, m.width, m.height)).toBuffer() : m.buf);

/** Writes <prefix><width>.{avif,webp,jpg} for every width that does not upscale; returns the widths. */
async function responsive(buf, srcWidth, dir, prefix, widths, quality) {
  // Never upscale: a smaller source additionally gets a variant at its full width.
  const fit = widths.filter((w) => w <= srcWidth);
  const unique = fit.length === widths.length ? fit : [...fit, srcWidth];
  for (const w of unique) {
    const base = sharp(buf).resize({ width: w, withoutEnlargement: true });
    await base.clone().avif({ quality: quality - 22, effort: 5 }).toFile(path.join(dir, `${prefix}${w}.avif`));
    await base.clone().webp({ quality }).toFile(path.join(dir, `${prefix}${w}.webp`));
    await base.clone().jpeg({ quality, mozjpeg: true, progressive: true }).toFile(path.join(dir, `${prefix}${w}.jpg`));
  }
  return unique;
}

const dominantColor = async (buf) => {
  const { dominant: d } = await sharp(buf).stats();
  return `rgb(${d.r},${d.g},${d.b})`;
};

/** Writes the web images and info.json; returns the rendered mockups ({ scene, buf }) for the exports. */
async function web(dir, m, img, { work, picked, details, fingerprint }) {
  // The folder only holds generated files, so start clean (drops mockups of scenes no longer picked).
  await fs.rm(dir, { recursive: true, force: true });
  await fs.mkdir(dir, { recursive: true });
  const widths = await responsive(m.buf, m.width, dir, '', img.web.widths, img.web.quality);
  const mockups = [];
  const rendered = [];
  const framed = picked.length ? await mockupSource(m) : null;
  for (const scene of picked) {
    const buf = await renderMockup(framed, work.size_cm, scene);
    rendered.push({ scene: scene.name, buf });
    const { width, height } = await sharp(buf).metadata();
    const mw = await responsive(buf, width, dir, `mockup-${scene.name}-`, img.mockups.widths, img.web.quality);
    mockups.push({ scene: scene.name, label: scene.label, width, height, widths: mw, dominant: await dominantColor(buf) });
  }
  const detailSets = [];
  for (const d of details) {
    const dm = await loadMaster(d.buf);
    const dw = await responsive(dm.buf, dm.width, dir, `detail-${d.name}-`, img.details.widths, img.web.quality);
    detailSets.push({ name: d.name, width: dm.width, height: dm.height, widths: dw, dominant: await dominantColor(dm.buf) });
  }
  const og = await shareImage(path.join(dir, 'og.jpg'), m, img);
  // Dimensions and placeholder colour, read by the site.
  const info = { width: m.width, height: m.height, widths, dominant: await dominantColor(m.buf), mockups, details: detailSets, og, fingerprint };
  await fs.writeFile(path.join(dir, 'info.json'), JSON.stringify(info, null, 2));
  return rendered;
}

/**
 * Share image of a work (og:image): the whole work on the paper background, never cropped (it is art),
 * in the 3:2 frame social networks show without cropping. Returns { width, height }.
 */
/** The whole image centred on the paper background in the share image size (images.og), as a JPEG buffer. */
async function wholeOnPaper(m, img) {
  const { width: W, height: H, background, padding, quality } = img.og;
  const pad = Math.round(H * padding);
  const inner = await sharp(m.buf).resize({ width: W - 2 * pad, height: H - 2 * pad, fit: 'inside', withoutEnlargement: true }).toBuffer();
  return sharp({ create: { width: W, height: H, channels: 3, background } })
    .composite([{ input: inner, gravity: 'center' }])
    .jpeg({ quality, mozjpeg: true })
    .toBuffer();
}

async function shareImage(file, m, img) {
  await fs.writeFile(file, await wholeOnPaper(m, img));
  return { width: img.og.width, height: img.og.height };
}

async function instagramClean(file, m, img) {
  const { width: W, height: H, background, padding } = img.instagram;
  const pad = Math.round(W * padding);
  const inner = await sharp(m.buf).resize({ width: W - 2 * pad, height: H - 2 * pad, fit: 'inside' }).toBuffer();
  await sharp({ create: { width: W, height: H, channels: 3, background } })
    .composite([{ input: inner, gravity: 'center' }])
    .jpeg({ quality: 92, mozjpeg: true })
    .toFile(file);
}

// A detail photo is a close-up, so it fills the whole 4:5 frame (centre crop) instead of sitting on paper.
async function instagramDetail(file, buf, img) {
  const { width: W, height: H } = img.instagram;
  await sharp(buf).rotate().toColorspace('srgb').resize(W, H, { fit: 'cover' }).jpeg({ quality: 92, mozjpeg: true }).toFile(file);
}

/** Resizes `buf` (the original or a mockup) for Fler and signs it with the author's name. */
async function fler(file, buf, img) {
  const f = img.fler;
  const resized = await sharp(buf).resize({ width: f.longEdge, height: f.longEdge, fit: 'inside', withoutEnlargement: true }).toBuffer();
  const { width, height } = await sharp(resized).metadata();
  const size = Math.round(Math.min(width, height) * 0.035);
  const margin = Math.round(size * 1.2);
  // Signature colour depends on the brightness of the corner: dark on light paper, light on dark paint.
  const cw = Math.round(width * 0.4), ch = Math.round(size * 2.5);
  const corner = await sharp(resized).extract({ left: width - cw, top: height - ch, width: cw, height: ch }).stats();
  const [r, g, b] = corner.channels.map((c) => c.mean);
  const light = 0.2126 * r + 0.7152 * g + 0.0722 * b > 150;
  const [ink, halo] = light ? ['#3a3430', '#ffffff'] : ['#ffffff', '#000000'];
  // Discreet signature in the bottom right corner, with a faint halo so it reads on light and dark areas.
  const mark = Buffer.from(`<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
    <style>text{font-family:'DejaVu Serif','Georgia',serif;font-style:italic;font-size:${size}px}</style>
    <text x="${width - margin + 1}" y="${height - margin + 1}" text-anchor="end" fill="${halo}" fill-opacity="${f.watermarkOpacity * 0.5}">${esc(f.watermark)}</text>
    <text x="${width - margin}" y="${height - margin}" text-anchor="end" fill="${ink}" fill-opacity="${f.watermarkOpacity}">${esc(f.watermark)}</text>
  </svg>`);
  await sharp(resized)
    .composite([{ input: mark }])
    .jpeg({ quality: f.quality, mozjpeg: true })
    .toFile(file);
}

/**
 * Web sizes of a standalone photo (site photo, collection cover) into `dir`, with info.json.
 * Skipped when the fingerprint is unchanged; returns true when the photo was (re)generated.
 */
async function photoSet(masterPath, dir, img, extra, { force, log, label }) {
  const master = await fs.readFile(masterPath);
  const fingerprint = sha1(String(PIPELINE_VERSION), master, JSON.stringify(extra));
  if ((await readJson(path.join(dir, 'info.json')))?.fingerprint === fingerprint && !force) return false;
  log(`→ ${label}`);
  const m = await loadMaster(master);
  await fs.rm(dir, { recursive: true, force: true });
  await fs.mkdir(dir, { recursive: true });
  const widths = await responsive(m.buf, m.width, dir, '', img.photos.widths, img.web.quality);
  const info = { width: m.width, height: m.height, widths, dominant: await dominantColor(m.buf), ...extra, fingerprint };
  await fs.writeFile(path.join(dir, 'info.json'), JSON.stringify(info, null, 2));
  return true;
}

/** Removes the sub-folders of `root` not in `wanted` (and `root` itself when it ends up empty). */
/** Removes files in `root` that are not in `wanted` (names), and `root` itself when it ends up empty. */
async function pruneFiles(root, wanted, rel, pruned) {
  if (!(await exists(root))) return;
  for (const f of await fs.readdir(root)) {
    if (!wanted.has(f)) {
      await fs.rm(path.join(root, f));
      pruned.push(`${rel}/${f}`);
    }
  }
  if ((await fs.readdir(root)).length === 0) await fs.rmdir(root);
}

async function pruneDirs(root, wanted, rel, pruned) {
  if (!(await exists(root))) return;
  for (const e of await fs.readdir(root, { withFileTypes: true })) {
    if (e.isDirectory() && !wanted.has(e.name)) {
      await fs.rm(path.join(root, e.name), { recursive: true });
      pruned.push(`${rel}/${e.name}/`);
    }
  }
  if ((await fs.readdir(root)).length === 0) await fs.rmdir(root);
}

/** Removes every export of one work (both platforms), so a regeneration never leaves stale files behind. */
async function clearExports(exportRoot, year, key) {
  const own = exportPattern(key);
  for (const sub of ['instagram', 'fler']) {
    const dir = path.join(exportRoot, sub, year);
    if (!(await exists(dir))) continue;
    for (const f of await fs.readdir(dir)) if (own.test(f)) await fs.rm(path.join(dir, f));
  }
}

/** Lists "<year>/<name>" entries one level below `root` (name without `ext` when given). */
async function listGenerated(root, ext) {
  const out = [];
  if (!(await exists(root))) return out;
  for (const year of await fs.readdir(root, { withFileTypes: true })) {
    if (!year.isDirectory()) continue;
    for (const e of await fs.readdir(path.join(root, year.name), { withFileTypes: true })) {
      if (ext ? e.isFile() && e.name.endsWith(ext) : e.isDirectory()) {
        out.push(`${year.name}/${ext ? e.name.slice(0, -ext.length) : e.name}`);
      }
    }
  }
  return out;
}

async function removeEmptyYearDirs(root) {
  if (!(await exists(root))) return;
  for (const year of await fs.readdir(root, { withFileTypes: true })) {
    const dir = path.join(root, year.name);
    if (year.isDirectory() && (await fs.readdir(dir)).length === 0) await fs.rmdir(dir);
  }
}

/**
 * Runs the whole pipeline. Returns a summary; throws on configuration errors.
 * Options: contentDir, siteDir, config, force, only (slugs), log, today, random, dataset, prepareOnly.
 * `prepareOnly` stops after skeletons, ids and checks: nothing is written to the site or the exports.
 * `dataset` 'real' (default) forbids test data in the content, 'demo' requires every item to be test data
 * (see scripts/lib/demo.mjs; test data are processed by `npm run demo` into .demo/, never into this repo).
 */
export async function run({
  contentDir,
  siteDir = siteRoot,
  config,
  force = false,
  only = [],
  scenesDir,
  log = console.log,
  today,
  random,
  dataset = 'real',
  prepareOnly = false,
} = {}) {
  config ??= YAML.parse(await fs.readFile(path.join(siteDir, 'site.config.yaml'), 'utf8'));
  const img = config.images;
  /**
   * Share image of a chosen cover ({ source, crop } from coverShareSource): cropped to crop.ratio around crop.focus
   * (filling the share image when the ratio is its own, 3:2, otherwise on paper), or without crop the whole image on
   * paper like the share image of a work; written only when it changed.
   */
  const shareCrop = async ({ source, crop }, file, label) => {
    const m = await loadMaster(await fs.readFile(source));
    const ogRatio = img.og.width / img.og.height;
    const area = crop && focusCrop(m.width, m.height, crop.ratio, crop.focus);
    // one lossy encoding only: the crop fills the share image in a single pipeline, or goes on paper as lossless PNG
    const buf = !crop
      ? await wholeOnPaper(m, img)
      : Math.abs(crop.ratio - ogRatio) < 0.01
        ? await sharp(m.buf).extract(area).resize(img.og.width, img.og.height).jpeg({ quality: img.og.quality, mozjpeg: true }).toBuffer()
        : await wholeOnPaper({ buf: await sharp(m.buf).extract(area).png().toBuffer(), width: area.width, height: area.height }, img);
    const old = await fs.readFile(file).catch(() => null);
    if (!old || !old.equals(buf)) {
      log(`→ ${label}`);
      await fs.mkdir(path.dirname(file), { recursive: true });
      await fs.writeFile(file, buf);
    }
  };
  contentDir ??= process.env.CONTENT_DIR || img.contentDir;
  if (!contentDir) throw new Error('Content location not set: put CONTENT_DIR=<path to the content repository> into .env');
  contentDir = path.resolve(siteDir, contentDir);
  if (!(await exists(path.join(contentDir, 'tvorba')))) {
    throw new Error(`Content not found: ${path.join(contentDir, 'tvorba')} (check CONTENT_DIR in .env)`);
  }

  const { works, collectionFolders, created, assigned, updated, pending, problems: scanProblems } = await prepareContent(contentDir, { today, random });
  const photos = await preparePhotos(contentDir);
  created.push(...photos.created);
  updated.push(...photos.updated);
  const collections = await prepareCollections(contentDir, collectionFolders);
  created.push(...collections.created);
  updated.push(...collections.updated);
  const years = await prepareYears(contentDir, works.map((w) => w.year).filter(Boolean), { demo: dataset === 'demo' });
  created.push(...years.created);
  updated.push(...years.updated);
  const home = await prepareHome(contentDir, { demo: dataset === 'demo' });
  created.push(...home.created);
  updated.push(...home.updated);
  created.forEach((p) => log(`+ new metadata skeleton: ${p}`));
  assigned.forEach((p) => log(`+ id assigned: ${p}`));
  updated.forEach((p) => log(`~ metadata brought in line with the schema: ${p}`));
  pending.forEach((p) => log(`! published, still marked DOPLNIT: ${p}`));
  const problems = [
    ...scanProblems, ...validateWorks(works), ...photos.problems, ...collections.problems, ...years.problems, ...home.problems,
    ...years.years.flatMap((y) => coverProblems({
      where: y.yamlPath, data: y.data, photoPath: y.coverPath, works, inScope: (w) => w.year === y.year, scope: y.year,
    })),
    ...(home.home ? coverProblems({ where: home.home.yamlPath, data: home.home.data, photoPath: home.home.coverPath, works }) : []),
    ...validateCollectionCovers(collections.collections, works),
    ...demoProblems({ works, collections: collections.collections, photos: photos.photos, years: years.years, home: home.home }, dataset),
  ];
  if (problems.length) {
    return { ok: false, problems, created, assigned, updated, pending, processed: 0, skipped: 0, missing: [], pruned: [], prepared: prepareOnly };
  }
  if (prepareOnly) return { ok: true, problems: [], created, assigned, updated, pending, processed: 0, skipped: 0, missing: [], pruned: [], prepared: true };
  const { scenes, text: scenesText } = await loadScenes(scenesDir);

  const metaRoot = path.join(siteDir, 'content/works');
  const webRoot = path.join(siteDir, 'public/works');
  const exportRoot = path.join(contentDir, 'export');

  let processed = 0, skipped = 0;
  const missing = [];
  for (const w of works) {
    if (only.length && !only.includes(w.slug)) continue;
    const key = workKey(w.slug, w.id);
    const rel = `${w.year}/${key}`;

    // Metadata copy for the site build, public fields only.
    // the collection comes from the folder of the work, the site reads it from the copy
    await writeIfChanged(path.join(metaRoot, `${rel}.yaml`), publicCopy({ ...w.data, collection: w.collection ?? undefined }, PUBLIC_WORK_FIELDS));

    const webDir = path.join(webRoot, rel);
    if (!w.masterPath) {
      // No master is fine as long as web images exist (another computer, CI).
      if (!(await exists(path.join(webDir, 'info.json')))) missing.push(rel);
      continue;
    }
    // Outputs depend on the master, the size (mockup scale), the scenes, whether the work is on sale
    // (Fler exports), `mockups`, `instagram` and the detail photos; not on price or description.
    const master = await fs.readFile(w.masterPath);
    const onSale = isOnSale(w.data.status);
    const instagram = wantsInstagram(w.data);
    const mockupsOn = wantsMockups(w.data);
    const details = await Promise.all(w.details.map(async (d) => ({ name: d.name, buf: await fs.readFile(d.path) })));
    const fingerprint = sha1(
      String(PIPELINE_VERSION), master, JSON.stringify(w.data.size_cm ?? null), scenesText, String(onSale), String(instagram), String(mockupsOn),
      ...details.flatMap((d) => [d.name, d.buf]),
    );
    const upToDate = (await readJson(path.join(webDir, 'info.json')))?.fingerprint === fingerprint;
    if (upToDate && !force) { skipped++; continue; }

    log(`→ ${rel}`);
    const m = await loadMaster(master);
    // Mockups only when the author asks for them (mockups: true), whether or not the work is for sale.
    const picked = mockupsOn ? pickScenes(w.data.size_cm, w.id, scenes) : [];
    if (mockupsOn && !picked.length) log(`  ! no mockup scene is big enough for ${rel} (see mockups/scenes.yaml maxCm)`);
    const mockups = await web(webDir, m, img, { work: w.data, picked, details, fingerprint });

    // Exports. Instagram: only when asked for (instagram: true), the original and the detail photos, never mockups.
    // Fler: only works on sale, the original and the mockups, all with the watermark.
    await clearExports(exportRoot, w.year, key);
    if (instagram) {
      const insta = path.join(exportRoot, 'instagram', w.year);
      await fs.mkdir(insta, { recursive: true });
      await instagramClean(path.join(insta, `${key}-clean.jpg`), m, img);
      for (const d of details) await instagramDetail(path.join(insta, `${key}-detail-${d.name}.jpg`), d.buf, img);
    }
    if (onSale) {
      const flerDir = path.join(exportRoot, 'fler', w.year);
      await fs.mkdir(flerDir, { recursive: true });
      await fler(path.join(flerDir, `${key}.jpg`), m.buf, img);
      for (const mk of mockups) await fler(path.join(flerDir, `${key}-mockup-${mk.scene}.jpg`), mk.buf, img);
    }
    processed++;
  }

  // Remove outputs of works that were deleted or renamed in the content repository.
  const pruned = [];
  if (!only.length) {
    // No works is a valid state (before the first real work); the tvorba/ folder itself must exist (checked above).
    const wanted = works.map((w) => `${w.year}/${workKey(w.slug, w.id)}`);
    for (const rel of planPrune(await listGenerated(metaRoot, '.yaml'), wanted)) {
      await fs.rm(path.join(metaRoot, `${rel}.yaml`));
      pruned.push(`content/works/${rel}.yaml`);
    }
    for (const rel of planPrune(await listGenerated(webRoot), wanted)) {
      await fs.rm(path.join(webRoot, rel), { recursive: true });
      pruned.push(`public/works/${rel}/`);
    }
    // Stale exports, independent of whether the work was regenerated in this run: exports of deleted or
    // renamed works, of detail photos and mockup scenes a work no longer has, Fler exports of works not on sale.
    const expected = new Map();
    for (const w of works) {
      const rel = `${w.year}/${workKey(w.slug, w.id)}`;
      const info = await readJson(path.join(webRoot, rel, 'info.json'));
      const mockupScenes = info ? (info.mockups ?? []).map((m) => m.scene) : null;
      expected.set(rel, expectedExports({ status: w.data.status, details: w.details.map((d) => d.name), mockupScenes, instagram: wantsInstagram(w.data) }));
    }
    for (const sub of ['instagram', 'fler']) {
      const root = path.join(exportRoot, sub);
      const wantedExports = new Map([...expected].map(([rel, e]) => [rel, e[sub]]));
      for (const rel of planExportPrune((await listGenerated(root, '.jpg')).map((f) => `${f}.jpg`), wantedExports)) {
        await fs.rm(path.join(root, rel));
        pruned.push(`export/${sub}/${rel}`);
      }
    }
    await removeEmptyYearDirs(metaRoot);
    await removeEmptyYearDirs(webRoot);
    for (const sub of ['instagram', 'fler']) await removeEmptyYearDirs(path.join(exportRoot, sub));
  }

  // Other photos (portrait, studio): public/photos/<name>/
  const photosRoot = path.join(siteDir, 'public/photos');
  for (const photo of photos.photos) {
    if (only.length && !only.includes(photo.name)) continue;
    const extra = { alt: photo.data.alt ?? '', caption: photo.data.caption ?? '', focus: photoFocus(photo.data) };
    if (await photoSet(photo.masterPath, path.join(photosRoot, photo.name), img, extra, { force, log, label: `fotky/${photo.name}` })) processed++;
    else skipped++;
  }
  if (!only.length) await pruneDirs(photosRoot, new Set(photos.photos.map((p) => p.name)), 'public/photos', pruned);

  // Collections: content/collections/<slug>.yaml (public fields) and public/collections/<slug>/ (cover photo).
  const collMetaRoot = path.join(siteDir, 'content/collections');
  const coversRoot = path.join(siteDir, 'public/collections');
  for (const c of collections.collections) {
    if (only.length && !only.includes(c.slug)) continue;
    await writeIfChanged(path.join(collMetaRoot, `${c.slug}.yaml`), publicCopy(c.data, PUBLIC_COLLECTION_FIELDS));
    const dir = path.join(coversRoot, c.slug);
    if (!c.coverPath) await fs.rm(dir, { recursive: true, force: true });
    else if (await photoSet(c.coverPath, dir, img, { alt: c.data.title ?? '' }, { force, log, label: `kolekce/${c.slug}` })) processed++;
    else skipped++;
  }
  // Share images of collections: the cover cropped exactly like the page shows it (3:2 around `focus`).
  // Cheap to render, so always rendered; written only when the bytes change.
  const ogRoot = path.join(siteDir, 'public/og/collections');
  const ogWanted = new Set();
  for (const c of collections.collections) {
    if (only.length && !only.includes(c.slug)) continue;
    const source = coverSource(c, works);
    if (!source) continue;
    ogWanted.add(`${c.slug}.jpg`);
    await shareCrop(source, path.join(ogRoot, `${c.slug}.jpg`), `og kolekce/${c.slug}`);
  }
  if (!only.length) {
    if (await exists(ogRoot)) {
      for (const f of await fs.readdir(ogRoot)) {
        if (!ogWanted.has(f)) {
          await fs.rm(path.join(ogRoot, f));
          pruned.push(`public/og/collections/${f}`);
        }
      }
      if ((await fs.readdir(ogRoot)).length === 0) {
        await fs.rmdir(ogRoot);
        const ogDir = path.dirname(ogRoot);
        if ((await fs.readdir(ogDir)).length === 0) await fs.rmdir(ogDir);
      }
    }
    const wanted = new Set(collections.collections.map((c) => c.slug));
    if (await exists(collMetaRoot)) {
      for (const f of await fs.readdir(collMetaRoot)) {
        if (f.endsWith('.yaml') && !wanted.has(f.slice(0, -5))) {
          await fs.rm(path.join(collMetaRoot, f));
          pruned.push(`content/collections/${f}`);
        }
      }
      if ((await fs.readdir(collMetaRoot)).length === 0) await fs.rmdir(collMetaRoot);
    }
    await pruneDirs(coversRoot, new Set(collections.collections.filter((c) => c.coverPath).map((c) => c.slug)), 'public/collections', pruned);
  }

  // Years: content/years/<year>.yaml (text and cover), public/years/<year>/ (own cover photo),
  // public/og/years/<year>.jpg (share image of a chosen cover, 3:2 around focus).
  const yearsRoot = path.join(siteDir, 'content/years');
  const yearPhotosRoot = path.join(siteDir, 'public/years');
  const yearOgRoot = path.join(siteDir, 'public/og/years');
  const yearOgWanted = new Set();
  for (const y of years.years) {
    if (only.length && !only.includes(y.year)) continue;
    await writeIfChanged(path.join(yearsRoot, `${y.year}.yaml`), publicCopy(y.data, PUBLIC_YEAR_FIELDS));
    const dir = path.join(yearPhotosRoot, y.year);
    if (!y.coverPath) {
      if (await exists(dir)) {
        await fs.rm(dir, { recursive: true, force: true });
        pruned.push(`public/years/${y.year}/`);
      }
    } else if (await photoSet(y.coverPath, dir, img, { alt: `Tvorba ${y.year}` }, { force, log, label: `roky/${y.year}` })) processed++;
    else skipped++;
    const source = coverShareSource({ photoPath: y.coverPath, data: y.data, works: works.filter((w) => w.year === y.year) });
    if (!source) continue;
    yearOgWanted.add(`${y.year}.jpg`);
    await shareCrop(source, path.join(yearOgRoot, `${y.year}.jpg`), `og roky/${y.year}`);
  }
  if (!only.length) {
    await pruneDirs(yearPhotosRoot, new Set(years.years.filter((y) => y.coverPath).map((y) => y.year)), 'public/years', pruned);
    await pruneFiles(yearOgRoot, yearOgWanted, 'public/og/years', pruned);
  }
  if (!only.length && (await exists(yearsRoot))) {
    const wantedYears = new Set(years.years.map((y) => `${y.year}.yaml`));
    for (const f of await fs.readdir(yearsRoot)) {
      if (!wantedYears.has(f)) {
        await fs.rm(path.join(yearsRoot, f));
        pruned.push(`content/years/${f}`);
      }
    }
    if ((await fs.readdir(yearsRoot)).length === 0) await fs.rmdir(yearsRoot);
  }

  // Home page: content/home.yaml (text and cover), public/home/ (own cover photo), public/og/home.jpg (chosen cover).
  if (home.home && !only.length) {
    const h = home.home;
    await writeIfChanged(path.join(siteDir, 'content/home.yaml'), publicCopy(h.data, PUBLIC_HOME_FIELDS));
    const dir = path.join(siteDir, 'public/home');
    if (!h.coverPath) {
      if (await exists(dir)) {
        await fs.rm(dir, { recursive: true, force: true });
        pruned.push('public/home/');
      }
    } else if (await photoSet(h.coverPath, dir, img, { alt: config.site?.title ?? '' }, { force, log, label: 'uvod' })) processed++;
    else skipped++;
    const source = coverShareSource({ photoPath: h.coverPath, data: h.data, works });
    const ogFile = path.join(siteDir, 'public/og/home.jpg');
    if (source) await shareCrop(source, ogFile, 'og uvod');
    else if (await exists(ogFile)) {
      await fs.rm(ogFile);
      pruned.push('public/og/home.jpg');
    }
  }
  pruned.forEach((p) => log(`- removed ${p}`));

  return { ok: missing.length === 0, problems: [], created, assigned, updated, pending, processed, skipped, missing, pruned };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const args = process.argv.slice(2);
  // On GitHub Actions the result is also written to the run page.
  const summary = (r, e) => process.env.GITHUB_STEP_SUMMARY && fs.appendFile(process.env.GITHUB_STEP_SUMMARY, formatSummary(r, e));
  try {
    // --demo: the content is the test data (dry run of the workflow on GitHub, see .github/workflows/dry-run.yml)
    const r = await run({
      force: args.includes('--force'),
      prepareOnly: args.includes('--prepare-only'),
      dataset: args.includes('--demo') ? 'demo' : 'real',
      only: args.filter((a) => !a.startsWith('--')),
    });
    r.problems.forEach((p) => console.error(`✗ ${p}`));
    if (r.problems.length === 0) console.log(r.prepared ? 'Prepared: skeletons, ids and checks only.' : `Done: ${r.processed} processed, ${r.skipped} unchanged.`);
    if (r.missing.length) console.error(`Missing master photo for: ${r.missing.join(', ')}`);
    await summary(r);
    if (!r.ok) process.exitCode = 1;
  } catch (e) {
    console.error(`✗ ${e.message}`);
    await summary(null, e);
    process.exitCode = 1;
  }
}
