import { test, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import YAML from 'yaml';
import { run } from './process-images.mjs';
import { sheetXmp } from './lib/sheet-box.mjs';
import { WORK_FIELDS } from './lib/works.mjs';
import { COLLECTION_FIELDS } from './lib/collections.mjs';
import { PHOTO_FIELDS } from './lib/photos.mjs';

const siteConfig = YAML.parse(await fs.readFile(new URL('../site.config.yaml', import.meta.url), 'utf8'));
// Small web widths keep the test fast.
const config = {
  ...siteConfig,
  images: {
    ...siteConfig.images,
    web: { widths: [40, 80], quality: 70 },
    mockups: { widths: [60] },
    details: { widths: [30] },
    photos: { widths: [40] },
    fler: { ...siteConfig.images.fler, longEdge: 120 },
  },
};

let tmp, contentDir, siteDir;
const exists = (p) => fs.access(p).then(() => true, () => false);
const quiet = () => {};
const opts = (over = {}) => ({ contentDir, siteDir, config, log: quiet, ...over });

// The content repository has no year folders: `year` only documents the date of the work.
async function addWork(year, slug, yaml, { image = true, collection = '' } = {}) {
  const dir = path.join(contentDir, 'tvorba', collection);
  await fs.mkdir(dir, { recursive: true });
  if (yaml !== undefined) await fs.writeFile(path.join(dir, `${slug}.yaml`), yaml);
  if (image) {
    await sharp({ create: { width: 64, height: 48, channels: 3, background: '#88aacc' } }).jpeg().toFile(path.join(dir, `${slug}.jpg`));
  }
}
/** Folder of the work with this slug: tvorba/ or its collection folder. */
async function workFolder(slug) {
  const root = path.join(contentDir, 'tvorba');
  if (await exists(path.join(root, `${slug}.yaml`))) return root;
  for (const e of await fs.readdir(root, { withFileTypes: true })) {
    if (e.isDirectory() && (await exists(path.join(root, e.name, `${slug}.yaml`)))) return path.join(root, e.name);
  }
  return root;
}
const idOf = async (year, slug) => YAML.parse(await fs.readFile(path.join(await workFolder(slug), `${slug}.yaml`), 'utf8')).id;

beforeEach(async () => {
  tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'pavla-pipeline-'));
  contentDir = path.join(tmp, 'pavla-content');
  siteDir = path.join(tmp, 'pavla');
  await fs.mkdir(path.join(contentDir, 'tvorba'), { recursive: true });
  await fs.mkdir(siteDir);
});
afterEach(() => fs.rm(tmp, { recursive: true, force: true }));

test('generates web images, metadata copy and exports under <year>/<slug>-<id>', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ninstagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  const r = await run(opts());
  assert.equal(r.ok, true);
  assert.equal(r.processed, 1);
  const key = `rano-${await idOf('2026', 'rano')}`;

  const info = JSON.parse(await fs.readFile(path.join(siteDir, 'public/works/2026', key, 'info.json'), 'utf8'));
  // The master is 64 px wide: 40 fits, 80 would upscale, so the full width is added instead.
  assert.deepEqual(info.widths, [40, 64]);
  for (const f of ['40.avif', '40.webp', '40.jpg', '64.jpg']) assert.ok(await exists(path.join(siteDir, 'public/works/2026', key, f)), f);

  const copy = await fs.readFile(path.join(siteDir, 'content/works/2026', `${key}.yaml`), 'utf8');
  assert.match(copy, /^# Generated by/);
  assert.equal(YAML.parse(copy).title, 'Ráno');

  for (const f of [`instagram/2026/${key}-clean.jpg`, `fler/2026/${key}.jpg`, `fler/2026/${key}-mockup-${info.mockups[0].scene}.jpg`]) {
    assert.ok(await exists(path.join(contentDir, 'export', f)), f);
  }
});

test('second run skips unchanged works; --force regenerates', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  const again = await run(opts());
  assert.equal(again.processed, 0);
  assert.equal(again.skipped, 1);
  const forced = await run(opts({ force: true }));
  assert.equal(forced.processed, 1);
});

test('a new image without metadata becomes a draft with generated outputs', async () => {
  await addWork('2026', 'novy', undefined);
  const r = await run(opts({ today: new Date('2026-05-01') }));
  assert.deepEqual(r.created, ['tvorba/novy.yaml']);
  const key = `novy-${await idOf('2026', 'novy')}`;
  assert.equal(YAML.parse(await fs.readFile(path.join(siteDir, 'content/works/2026', `${key}.yaml`), 'utf8')).draft, true);
  assert.ok(await exists(path.join(siteDir, 'public/works/2026', key, 'info.json')));
});

test('renaming a work keeps its id and removes the old outputs', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ninstagram: true\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const dir = path.join(contentDir, 'tvorba');
  await fs.rename(path.join(dir, 'rano.yaml'), path.join(dir, 'rano-u-rybnika.yaml'));
  await fs.rename(path.join(dir, 'rano.jpg'), path.join(dir, 'rano-u-rybnika.jpg'));

  const r = await run(opts());
  assert.deepEqual(r.pruned.sort(), [
    `content/works/2026/rano-${id}.yaml`, `export/instagram/2026/rano-${id}-clean.jpg`, `public/works/2026/rano-${id}/`,
  ]);
  assert.ok(await exists(path.join(siteDir, 'public/works/2026', `rano-u-rybnika-${id}`, 'info.json')));
  assert.ok(!(await exists(path.join(siteDir, 'public/works/2026', `rano-${id}`))));
});

test('deleting the last work of a year removes the empty year folders', async () => {
  await addWork('2025', 'stary', 'title: Starý\ndate: 2025-03-01\n');
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  for (const f of ['stary.yaml', 'stary.jpg']) await fs.rm(path.join(contentDir, 'tvorba', f));
  await run(opts());
  assert.ok(!(await exists(path.join(siteDir, 'public/works/2025'))));
  assert.ok(!(await exists(path.join(siteDir, 'content/works/2025'))));
});

test('a work without master keeps existing outputs and reports missing ones', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  await fs.rm(path.join(contentDir, 'tvorba/rano.jpg'));
  const kept = await run(opts());
  assert.equal(kept.ok, true);
  assert.deepEqual(kept.pruned, []);

  await addWork('2026', 'bez-fotky', 'title: Bez fotky\ndate: 2026-01-01\n', { image: false });
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.deepEqual(r.missing, [`2026/bez-fotky-${await idOf('2026', 'bez-fotky')}`]);
});

test('validation problems stop the run before anything is written to the site', async () => {
  await addWork('2026', 'spatne-datum', 'title: Špatné datum\ndate: 14. 6. 2026\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems[0], /tvorba\/spatne-datum\.yaml: date must be a day like 2026-06-14/);
  assert.ok(!(await exists(path.join(siteDir, 'public/works'))));
  assert.ok(!(await exists(path.join(siteDir, 'content/works'))));
});

test('only=<slug> processes one work and never prunes', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-15\n');
  const r = await run(opts({ only: ['vecer'] }));
  assert.equal(r.processed, 1);
  assert.ok(!(await exists(path.join(siteDir, 'public/works/2026', `rano-${await idOf('2026', 'rano')}`))));
});

test('no works (before the first real work) is fine and removes all generated works', async () => {
  assert.equal((await run(opts())).ok, true);
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  for (const f of ['rano.yaml', 'rano.jpg']) await fs.rm(path.join(contentDir, 'tvorba', f));
  const r = await run(opts());
  assert.equal(r.ok, true);
  assert.ok(!(await exists(path.join(siteDir, 'public/works/2026'))));
  assert.ok(!(await exists(path.join(siteDir, 'content/works/2026'))));
});

test('fails clearly when the content repository is missing', async () => {
  await assert.rejects(run(opts({ contentDir: path.join(tmp, 'nothing') })), /Content not found/);
});

const infoOf = async (year, slug) =>
  JSON.parse(await fs.readFile(path.join(siteDir, 'public/works', year, `${slug}-${await idOf(year, slug)}`, 'info.json'), 'utf8'));
const setYaml = async (year, slug, text) => fs.writeFile(path.join(await workFolder(slug), `${slug}.yaml`), text);

test('generates three mockups and lists them in info.json', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const info = await infoOf('2026', 'rano');
  assert.equal(info.mockups.length, 3);
  assert.equal(new Set(info.mockups.map((m) => m.scene)).size, 3);
  const dir = path.join(siteDir, 'public/works/2026', `rano-${await idOf('2026', 'rano')}`);
  for (const m of info.mockups) {
    assert.ok(m.label);
    for (const ext of ['avif', 'webp', 'jpg']) assert.ok(await exists(path.join(dir, `mockup-${m.scene}-60.${ext}`)), `${m.scene} ${ext}`);
  }
});

test('changing size_cm regenerates the work, changing the price does not', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const before = (await infoOf('2026', 'rano')).fingerprint;

  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nstatus: available\nsize_cm: [40, 30]\nmockups: true\nprice: 3200\n`);
  assert.equal((await run(opts())).processed, 0);

  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nstatus: available\nsize_cm: [20, 15]\nmockups: true\nprice: 3200\n`);
  const r = await run(opts());
  assert.equal(r.processed, 1);
  const after = await infoOf('2026', 'rano');
  assert.notEqual(after.fingerprint, before);
  // A 20 × 15 cm work is small: shelf and desk instead of living room and hallway.
  assert.deepEqual(after.mockups.slice(1).map((m) => m.scene), ['police', 'pracovna']);
});

test('regeneration removes mockups of scenes that are no longer picked', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [56, 38]\nmockups: true\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const dir = path.join(siteDir, 'public/works/2026', `rano-${id}`);
  const old = (await infoOf('2026', 'rano')).mockups.map((m) => m.scene);
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [20, 15]\nmockups: true\n`);
  await run(opts());
  const now = (await infoOf('2026', 'rano')).mockups.map((m) => m.scene);
  for (const scene of old.filter((s) => !now.includes(s))) {
    assert.ok(!(await exists(path.join(dir, `mockup-${scene}-60.jpg`))), scene);
  }
});

async function addPhoto(name, yaml) {
  const dir = path.join(contentDir, 'fotky');
  await fs.mkdir(dir, { recursive: true });
  await sharp({ create: { width: 50, height: 70, channels: 3, background: '#c9b79c' } }).jpeg().toFile(path.join(dir, `${name}.jpg`));
  if (yaml !== undefined) await fs.writeFile(path.join(dir, `${name}.yaml`), yaml);
}

test('photos: a new photo gets a skeleton description and web sizes', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addPhoto('portret');
  const r = await run(opts());
  assert.ok(r.created.includes('fotky/portret.yaml'));
  const info = JSON.parse(await fs.readFile(path.join(siteDir, 'public/photos/portret/info.json'), 'utf8'));
  assert.equal(info.alt, 'Portret');
  assert.deepEqual(info.widths, [40]);
  assert.ok(await exists(path.join(siteDir, 'public/photos/portret/40.avif')));
});

test('photos: editing the description updates info.json, deleting the photo removes it', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addPhoto('atelier', 'alt: Ateliér\ncaption: Kde maluji\n');
  await run(opts());
  await fs.writeFile(path.join(contentDir, 'fotky/atelier.yaml'), 'alt: Ateliér u okna\ncaption: Kde maluji\n');
  await run(opts());
  const info = JSON.parse(await fs.readFile(path.join(siteDir, 'public/photos/atelier/info.json'), 'utf8'));
  assert.equal(info.alt, 'Ateliér u okna');

  await fs.rm(path.join(contentDir, 'fotky/atelier.jpg'));
  await fs.rm(path.join(contentDir, 'fotky/atelier.yaml'));
  const r = await run(opts());
  assert.ok(r.pruned.includes('public/photos/atelier/'));
  assert.ok(!(await exists(path.join(siteDir, 'public/photos/atelier'))));
});

test('photos: a description without a photo is reported', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await fs.mkdir(path.join(contentDir, 'fotky'));
  await fs.writeFile(path.join(contentDir, 'fotky/sirotek.yaml'), 'alt: x\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems[0], /no photo named "sirotek"/);
});


const workDir = async (year, slug) => path.join(siteDir, 'public/works', year, `${slug}-${await idOf(year, slug)}`);
/** Export file names of a work on one platform (instagram | fler), without the "<key>" prefix. */
const exportsOf = async (sub, year, slug) => {
  const key = `${slug}-${await idOf(year, slug)}`;
  const dir = path.join(contentDir, 'export', sub, year);
  if (!(await exists(dir))) return [];
  return (await fs.readdir(dir)).filter((f) => f.startsWith(key)).map((f) => f.slice(key.length)).sort();
};

test('mockups: only works with mockups: true get them, whatever their status', async () => {
  const yaml = (title, status, extra) => `title: ${title}\ndate: 2026-06-14\nstatus: ${status}\n${status === 'available' || status === 'reserved' ? 'price: 1000\n' : ''}size_cm: [40, 30]\n${extra}`;
  await addWork('2026', 'volny', yaml('Volný', 'available', 'mockups: true\n'));
  await addWork('2026', 'volny-bez', yaml('Volný bez', 'available', 'mockups: false\n'));
  await addWork('2026', 'doma', yaml('Doma', 'not-for-sale', 'mockups: true\n'));
  await addWork('2026', 'prodany', yaml('Prodaný', 'sold', 'mockups: true\n'));
  await addWork('2026', 'bez-pole', yaml('Bez pole', 'reserved', ''));
  assert.equal((await run(opts())).ok, true);
  for (const slug of ['volny', 'doma', 'prodany']) assert.equal((await infoOf('2026', slug)).mockups.length, 3, slug);
  for (const slug of ['volny-bez', 'bez-pole']) {
    assert.deepEqual((await infoOf('2026', slug)).mockups, [], slug);
    assert.ok(!(await fs.readdir(await workDir('2026', slug))).some((f) => f.startsWith('mockup-')), slug);
  }
  // Fler follows the status: works on sale get the original and their mockups, others nothing
  assert.equal((await exportsOf('fler', '2026', 'volny')).length, 4);
  assert.deepEqual(await exportsOf('fler', '2026', 'volny-bez'), ['.jpg']);
  assert.deepEqual(await exportsOf('fler', '2026', 'bez-pole'), ['.jpg']);
  for (const slug of ['doma', 'prodany']) assert.deepEqual(await exportsOf('fler', '2026', slug), [], slug);
  // the public copy carries the flag, the page reads it
  const copy = YAML.parse(await fs.readFile(path.join(siteDir, 'content/works/2026', `doma-${await idOf('2026', 'doma')}.yaml`), 'utf8'));
  assert.equal(copy.mockups, true);
});

test('mockups: selling a work removes its Fler exports but keeps its mockups; mockups: false removes them', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ninstagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  assert.equal((await infoOf('2026', 'rano')).mockups.length, 3);
  assert.equal((await exportsOf('fler', '2026', 'rano')).length, 4);

  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\ninstagram: true\nstatus: sold\nsize_cm: [40, 30]\nmockups: true\n`);
  assert.equal((await run(opts())).processed, 1);
  assert.equal((await infoOf('2026', 'rano')).mockups.length, 3, 'a sold work keeps its mockups');
  assert.deepEqual(await exportsOf('fler', '2026', 'rano'), []);
  assert.ok(await exists(path.join(contentDir, 'export/instagram/2026', `rano-${id}-clean.jpg`)));

  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\ninstagram: true\nstatus: sold\nsize_cm: [40, 30]\nmockups: false\n`);
  assert.equal((await run(opts())).processed, 1);
  assert.deepEqual((await infoOf('2026', 'rano')).mockups, []);
  assert.ok(!(await fs.readdir(await workDir('2026', 'rano'))).some((f) => f.startsWith('mockup-')));

  // available → reserved changes nothing that is generated
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n`);
  await run(opts());
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nstatus: reserved\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n`);
  assert.equal((await run(opts())).processed, 0);
});

test('validation: mockups must be true or false', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmockups: ano\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /mockups must be true or false/);
});

async function addDetail(year, slug, file, color = '#aa6644') {
  const dir = path.join(await workFolder(slug), slug);
  await fs.mkdir(dir, { recursive: true });
  await sharp({ create: { width: 40, height: 40, channels: 3, background: color } }).jpeg().toFile(path.join(dir, file));
}

test('details: detail photos get web sizes and are listed in info.json in file name order', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addDetail('2026', 'rano', '2-lodka.jpg');
  await addDetail('2026', 'rano', '1 Květ.jpg');
  assert.equal((await run(opts())).ok, true);
  const info = await infoOf('2026', 'rano');
  assert.deepEqual(info.details.map((d) => d.name), ['1-kvet', '2-lodka']);
  assert.deepEqual(info.details[0].widths, [30]);
  for (const ext of ['avif', 'webp', 'jpg']) assert.ok(await exists(path.join(await workDir('2026', 'rano'), `detail-1-kvet-30.${ext}`)), ext);
});

test('details: adding, changing or removing a detail photo regenerates the work', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  assert.deepEqual((await infoOf('2026', 'rano')).details, []);

  await addDetail('2026', 'rano', 'kvet.jpg');
  assert.equal((await run(opts())).processed, 1);
  assert.equal((await run(opts())).processed, 0);

  await addDetail('2026', 'rano', 'kvet.jpg', '#113355');
  assert.equal((await run(opts())).processed, 1);

  await fs.rm(path.join(contentDir, 'tvorba/rano'), { recursive: true });
  assert.equal((await run(opts())).processed, 1);
  assert.deepEqual((await infoOf('2026', 'rano')).details, []);
  assert.ok(!(await fs.readdir(await workDir('2026', 'rano'))).some((f) => f.startsWith('detail-')));
});

test('private note: never reaches the site repository, not even through comments', async () => {
  await addWork('2026', 'rano', [
    '# koupila teta, nikomu neříkat',
    'title: Ráno',
    'date: 2026-06-14',
    'description: Veřejný popis.',
    'private_note: |',
    '  Soukromá poznámka.',
    'poznamka: vymyšlené pole',
    '',
  ].join('\n'));
  await run(opts());
  const key = `rano-${await idOf('2026', 'rano')}`;
  const copy = await fs.readFile(path.join(siteDir, 'content/works/2026', `${key}.yaml`), 'utf8');
  assert.doesNotMatch(copy, /Soukromá|private_note|teta|vymyšlené/);
  assert.deepEqual(YAML.parse(copy), { id: key.slice(-5), title: 'Ráno', date: '2026-06-14', description: 'Veřejný popis.' });
  // the private repository keeps the note
  assert.match(await fs.readFile(path.join(contentDir, 'tvorba/rano.yaml'), 'utf8'), /Soukromá poznámka/);
});

/** A file of a collection folder (tvorba/<collection>/). */
const collFile = (coll, name) => path.join(contentDir, 'tvorba', coll, name);
const setCollection = async (coll, text) => {
  await fs.mkdir(path.join(contentDir, 'tvorba', coll), { recursive: true });
  await fs.writeFile(collFile(coll, '_kolekce.yaml'), text);
};
async function addCover(coll) {
  await fs.mkdir(path.join(contentDir, 'tvorba', coll), { recursive: true });
  await sharp({ create: { width: 60, height: 40, channels: 3, background: '#557744' } }).jpeg().toFile(collFile(coll, '_uvod.jpg'));
}

test('collections: a folder in tvorba/ is a collection, gets a skeleton titled after it and a public copy', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: '2026-plener-sumava' });
  await addWork('2025', 'kvet', 'title: Květ\ndate: 2025-05-01\n', { collection: '2025 Jaro na zahradě' });
  await addWork('2026', 'sam', 'title: Sám\ndate: 2026-01-01\n');
  const r = await run(opts());
  assert.equal(r.ok, true, r.problems.join('\n'));
  assert.ok(r.created.includes('tvorba/2026-plener-sumava/_kolekce.yaml'));
  // a leading year moves to the end of the title, the slug comes from the folder name
  assert.equal(YAML.parse(await fs.readFile(collFile('2026-plener-sumava', '_kolekce.yaml'), 'utf8')).title, 'Plener sumava 2026');
  assert.equal(YAML.parse(await fs.readFile(collFile('2025 Jaro na zahradě', '_kolekce.yaml'), 'utf8')).title, 'Jaro na zahradě 2025');
  assert.ok(await exists(path.join(siteDir, 'content/collections/2025-jaro-na-zahrade.yaml')));
  // the collection of a work comes from its folder; a work in tvorba/ has none
  const copyOf = async (year, slug) => YAML.parse(await fs.readFile(path.join(siteDir, 'content/works', year, `${slug}-${await idOf(year, slug)}.yaml`), 'utf8'));
  assert.equal((await copyOf('2026', 'rano')).collection, '2026-plener-sumava');
  assert.equal((await copyOf('2026', 'sam')).collection, undefined);

  await setCollection('2026-plener-sumava', 'title: Plenér Šumava 2026\ndescription: Týden na Kvildě.\nprivate_note: tajné\n');
  await run(opts());
  const copy = await fs.readFile(path.join(siteDir, 'content/collections/2026-plener-sumava.yaml'), 'utf8');
  assert.deepEqual(YAML.parse(copy), { title: 'Plenér Šumava 2026', description: 'Týden na Kvildě.' });
  assert.doesNotMatch(copy, /tajné/);
  // no cover photo, no cover folder
  assert.ok(!(await exists(path.join(siteDir, 'public/collections/2026-plener-sumava'))));
});

test('collections: a collection may span years, its works keep their own years', async () => {
  await addWork('2025', 'prosinec', 'title: Prosinec\ndate: 2025-12-30\n', { collection: '2025-2026-zima' });
  await addWork('2026', 'leden', 'title: Leden\ndate: 2026-01-02\n', { collection: '2025-2026-zima' });
  assert.equal((await run(opts())).ok, true);
  assert.equal(YAML.parse(await fs.readFile(collFile('2025-2026-zima', '_kolekce.yaml'), 'utf8')).title, 'Zima 2025–2026');
  assert.ok(await exists(path.join(siteDir, 'content/works/2025', `prosinec-${await idOf('2025', 'prosinec')}.yaml`)));
  assert.ok(await exists(path.join(siteDir, 'content/works/2026', `leden-${await idOf('2026', 'leden')}.yaml`)));
});

test('collections: a cover photo (_uvod.jpg) gets web sizes; removing it or the collection cleans up', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener' });
  await addCover('plener');
  await setCollection('plener', 'title: Plenér\n');
  await run(opts());
  const info = JSON.parse(await fs.readFile(path.join(siteDir, 'public/collections/plener/info.json'), 'utf8'));
  assert.equal(info.alt, 'Plenér');
  assert.deepEqual(info.widths, [40]);
  assert.equal((await run(opts())).processed, 0);

  await fs.rm(collFile('plener', '_uvod.jpg'));
  await run(opts());
  assert.ok(!(await exists(path.join(siteDir, 'public/collections/plener'))));
  assert.ok(await exists(path.join(siteDir, 'content/collections/plener.yaml')));

  await fs.rm(path.join(contentDir, 'tvorba/plener'), { recursive: true });
  const r = await run(opts());
  assert.ok(r.pruned.includes('content/collections/plener.yaml'));
  assert.ok(!(await exists(path.join(siteDir, 'content/collections'))));
});

test('collections: a folder with just a cover photo is a collection with a skeleton too', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addCover('jaro-na-zahrade');
  const r = await run(opts());
  assert.ok(r.created.includes('tvorba/jaro-na-zahrade/_kolekce.yaml'));
  assert.equal(YAML.parse(await fs.readFile(collFile('jaro-na-zahrade', '_kolekce.yaml'), 'utf8')).title, 'Jaro na zahrade');
});

test('collections: collection:, a missing title, nested collections, clashing names and kolekce/ stop the run', async () => {
  const problemsOf = async () => {
    const r = await run(opts());
    assert.equal(r.ok, false);
    return r.problems.join('\n');
  };
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ncollection: plener\n');
  assert.match(await problemsOf(), /tvorba\/rano\.yaml: "collection:" is not used any more, a work belongs to a collection by lying in its folder/);
  await setYaml('2026', 'rano', `id: ${await idOf('2026', 'rano')}\ntitle: Ráno\ndate: 2026-06-14\n`);

  await setCollection('plener', 'description: bez názvu\n');
  assert.match(await problemsOf(), /tvorba\/plener\/_kolekce\.yaml: missing title/);
  await setCollection('plener', 'title: Plenér\n');

  await addWork('2026', 'vnoreny', 'title: V\ndate: 2026-06-14\n', { collection: 'plener/podkolekce' });
  assert.match(await problemsOf(), /tvorba\/plener\/podkolekce\/: .*collections cannot be nested/);
  await fs.rm(path.join(contentDir, 'tvorba/plener/podkolekce'), { recursive: true });

  await setCollection('Plenér', 'title: Druhý plenér\n');
  assert.match(await problemsOf(), /gives the same web address "plener"/);
  await fs.rm(path.join(contentDir, 'tvorba/Plenér'), { recursive: true });

  await fs.mkdir(path.join(contentDir, 'kolekce'));
  assert.match(await problemsOf(), /kolekce\/: collections are folders in tvorba\/ now/);
  await fs.rm(path.join(contentDir, 'kolekce'), { recursive: true });
  assert.equal((await run(opts())).ok, true);
});

test('exports: Instagram gets the original on paper and the detail photos in 4:5, never mockups', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ninstagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await addDetail('2026', 'rano', '1-kvet.jpg');
  await addDetail('2026', 'rano', '2-lodka.jpg');
  await run(opts());
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), ['-clean.jpg', '-detail-1-kvet.jpg', '-detail-2-lodka.jpg']);
  const { width: W, height: H } = config.images.instagram;
  for (const f of await exportsOf('instagram', '2026', 'rano')) {
    const { width, height } = await sharp(path.join(contentDir, 'export/instagram/2026', `rano-${await idOf('2026', 'rano')}${f}`)).metadata();
    assert.deepEqual([width, height], [W, H], f);
  }
});

test('exports: Fler gets the original and every mockup with the watermark, only for works on sale', async () => {
  await addWork('2026', 'volny', 'title: Volný\ndate: 2026-06-14\ninstagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await addDetail('2026', 'volny', 'kvet.jpg');
  await addWork('2026', 'doma', 'title: Doma\ndate: 2026-06-14\ninstagram: true\nstatus: not-for-sale\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const scenes = (await infoOf('2026', 'volny')).mockups.map((m) => `-mockup-${m.scene}.jpg`);
  assert.deepEqual(await exportsOf('fler', '2026', 'volny'), ['.jpg', ...scenes].sort());
  // the watermark changes the pixels of the bottom right corner against a plain resize of the same image
  const key = `volny-${await idOf('2026', 'volny')}`;
  const flerFile = path.join(contentDir, 'export/fler/2026', `${key}.jpg`);
  const { width, height } = await sharp(flerFile).metadata();
  const plain = await sharp(path.join(contentDir, 'tvorba/volny.jpg')).resize(width, height).raw().toBuffer();
  const signed = await sharp(flerFile).raw().toBuffer();
  assert.notDeepEqual(signed, plain);
  // a work that is not for sale has Instagram exports only
  assert.deepEqual(await exportsOf('fler', '2026', 'doma'), []);
  assert.deepEqual(await exportsOf('instagram', '2026', 'doma'), ['-clean.jpg']);
});

test('exports: removing a detail photo removes its Instagram export', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ninstagram: true\n');
  await addDetail('2026', 'rano', 'kvet.jpg');
  await run(opts());
  await fs.rm(path.join(contentDir, 'tvorba/rano'), { recursive: true });
  await run(opts());
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), ['-clean.jpg']);
});

test('validation: a work on sale without a price stops the run', async () => {
  await addWork('2026', 'bez-ceny', 'title: Bez ceny\ndate: 2026-06-14\nstatus: reserved\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /status "reserved" needs a price/);
});

test('detail captions: a caption for a missing detail photo stops the run, valid captions reach the public copy', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ndetails:\n  1 Květ: Květ zblízka\n  lodka: Loďka\n');
  await addDetail('2026', 'rano', '1-kvet.jpg');
  let r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /no detail photo "lodka"/);

  await addDetail('2026', 'rano', 'lodka.jpg');
  r = await run(opts());
  assert.equal(r.ok, true);
  const key = `rano-${await idOf('2026', 'rano')}`;
  const copy = YAML.parse(await fs.readFile(path.join(siteDir, 'content/works/2026', `${key}.yaml`), 'utf8'));
  assert.deepEqual(copy.details, { '1 Květ': 'Květ zblízka', lodka: 'Loďka' });
});

test('exports: renaming or deleting a work removes its old exports on both platforms', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ninstagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await addDetail('2026', 'rano', 'kvet.jpg');
  await addWork('2025', 'stary', 'title: Starý\ndate: 2025-03-01\ninstagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const oldId = await idOf('2025', 'stary');
  const flerBefore = await exportsOf('fler', '2026', 'rano');
  const stareFler = await exportsOf('fler', '2025', 'stary');
  assert.equal(flerBefore.length, 4);
  assert.equal(stareFler.length, 4);

  // rename: same id, new slug (the detail folder moves with it)
  const dir = path.join(contentDir, 'tvorba');
  for (const [from, to] of [['rano.yaml', 'rano-u-rybnika.yaml'], ['rano.jpg', 'rano-u-rybnika.jpg'], ['rano', 'rano-u-rybnika']]) {
    await fs.rename(path.join(dir, from), path.join(dir, to));
  }
  // delete: the work of 2025
  for (const f of ['stary.yaml', 'stary.jpg']) await fs.rm(path.join(contentDir, 'tvorba', f));

  const r = await run(opts());
  const exportsPruned = r.pruned.filter((p) => p.startsWith('export/')).sort();
  assert.deepEqual(exportsPruned, [
    ...flerBefore.map((f) => `export/fler/2026/rano-${id}${f}`),
    `export/instagram/2026/rano-${id}-clean.jpg`,
    `export/instagram/2026/rano-${id}-detail-kvet.jpg`,
    ...stareFler.map((f) => `export/fler/2025/stary-${oldId}${f}`),
    `export/instagram/2025/stary-${oldId}-clean.jpg`,
  ].sort());
  // nothing of the old names is left, the renamed work has fresh exports
  for (const sub of ['instagram', 'fler']) {
    const all = await fs.readdir(path.join(contentDir, 'export', sub, '2026'));
    assert.ok(all.every((f) => f.startsWith(`rano-u-rybnika-${id}`)), `${sub}: ${all}`);
    assert.ok(!(await exists(path.join(contentDir, 'export', sub, '2025'))), `${sub}/2025 removed`);
  }
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano-u-rybnika'), ['-clean.jpg', '-detail-kvet.jpg']);
  assert.equal((await exportsOf('fler', '2026', 'rano-u-rybnika')).length, 4);
});

test('exports: only=<slug> never prunes exports, unknown files in export/ are left alone', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ninstagram: true\n');
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-15\ninstagram: true\n');
  await run(opts());
  const vecerId = await idOf('2026', 'vecer');
  await fs.writeFile(path.join(contentDir, 'export/instagram/2026/poznamky.txt'), 'x');
  await fs.rm(path.join(contentDir, 'tvorba/vecer.yaml'));
  await fs.rm(path.join(contentDir, 'tvorba/vecer.jpg'));

  await run(opts({ only: ['rano'] }));
  assert.ok(await exists(path.join(contentDir, 'export/instagram/2026', `vecer-${vecerId}-clean.jpg`)));

  const r = await run(opts());
  assert.ok(r.pruned.includes(`export/instagram/2026/vecer-${vecerId}-clean.jpg`));
  assert.ok(await exists(path.join(contentDir, 'export/instagram/2026/poznamky.txt')));
});

test('exports: a stale detail export is removed even when the work is not regenerated', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ninstagram: true\n');
  await addDetail('2026', 'rano', 'kvet.jpg');
  await run(opts());
  const id = await idOf('2026', 'rano');
  // e.g. left behind by an interrupted run or an older pipeline version
  const stale = path.join(contentDir, 'export/instagram/2026', `rano-${id}-detail-lodka.jpg`);
  await fs.copyFile(path.join(contentDir, 'export/instagram/2026', `rano-${id}-detail-kvet.jpg`), stale);

  const r = await run(opts());
  assert.equal(r.processed, 0);
  assert.deepEqual(r.pruned, [`export/instagram/2026/rano-${id}-detail-lodka.jpg`]);
  assert.ok(!(await exists(stale)));
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), ['-clean.jpg', '-detail-kvet.jpg']);
});

test('exports: stale Fler exports are removed even when the work is not regenerated', async () => {
  await addWork('2026', 'volny', 'title: Volný\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await addWork('2026', 'doma', 'title: Doma\ndate: 2026-06-14\nstatus: not-for-sale\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const flerDir = path.join(contentDir, 'export/fler/2026');
  const volny = `volny-${await idOf('2026', 'volny')}`;
  const doma = `doma-${await idOf('2026', 'doma')}`;
  // e.g. left behind by an interrupted run: a mockup of a scene the work does not have,
  // Fler exports of a work that is not for sale, an Instagram mockup (never allowed)
  const src = path.join(flerDir, `${volny}.jpg`);
  const stale = [
    path.join(flerDir, `${volny}-mockup-zahrada.jpg`),
    path.join(flerDir, `${doma}.jpg`),
    path.join(flerDir, `${doma}-mockup-police.jpg`),
    path.join(contentDir, 'export/instagram/2026', `${volny}-wall.jpg`),
  ];
  for (const f of stale) {
    await fs.mkdir(path.dirname(f), { recursive: true }); // no work asks for Instagram, the folder does not exist
    await fs.copyFile(src, f);
  }

  const r = await run(opts());
  assert.equal(r.processed, 0);
  assert.deepEqual(r.pruned.sort(), stale.map((f) => path.relative(contentDir, f)).sort());
  for (const f of stale) assert.ok(!(await exists(f)), f);
  assert.equal((await exportsOf('fler', '2026', 'volny')).length, 4);
});

test('collections: cover names a published work of the collection and reaches the public copy', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener' });
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-20\n', { collection: 'plener' });
  await addWork('2026', 'jinde', 'title: Jinde\ndate: 2026-06-21\n');
  await addWork('2026', 'skica', 'title: Skica\ndate: 2026-06-22\ndraft: true\n', { collection: 'plener' });
  await run(opts());
  const [rano, jinde, skica] = await Promise.all(['rano', 'jinde', 'skica'].map((s) => idOf('2026', s)));
  const setCover = (cover) => setCollection('plener', `title: Plenér\ncover: ${cover}\n`);

  await setCover(rano);
  assert.equal((await run(opts())).ok, true);
  assert.equal(YAML.parse(await fs.readFile(path.join(siteDir, 'content/collections/plener.yaml'), 'utf8')).cover, rano);

  const problemFor = async (cover) => {
    await setCover(cover);
    const r = await run(opts());
    assert.equal(r.ok, false, cover);
    return r.problems.join('\n');
  };
  assert.match(await problemFor('zzzzz'), /cover zzzzz: zzzzz is not the id of any work/);
  assert.match(await problemFor(jinde), /\(Jinde\) is not in this collection/);
  assert.match(await problemFor(skica), /\(Skica\) is a draft/);

  await setCover(rano);
  await addCover('plener');
  assert.match((await run(opts())).problems.join('\n'), /cover .* and the cover photo _uvod\.jpg both set/);
});

test('photos: focus goes to info.json (centre by default), an invalid focus stops the run', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addPhoto('portret');
  await addPhoto('o-mne-uvod', 'alt: Plenér\nfocus: [80, 65]\n');
  await run(opts());
  const infoOfPhoto = async (name) => JSON.parse(await fs.readFile(path.join(siteDir, 'public/photos', name, 'info.json'), 'utf8'));
  assert.deepEqual((await infoOfPhoto('portret')).focus, [50, 50]); // skeleton says [50, 50]
  assert.deepEqual((await infoOfPhoto('o-mne-uvod')).focus, [80, 65]);

  for (const focus of ['[120, 50]', '[50]', '"vpravo"', '[a, b]']) {
    await fs.writeFile(path.join(contentDir, 'fotky/o-mne-uvod.yaml'), `alt: Plenér\nfocus: ${focus}\n`);
    const r = await run(opts());
    assert.equal(r.ok, false, focus);
    assert.match(r.problems.join('\n'), /fotky\/o-mne-uvod\.yaml: focus must be \[x, y\]/, focus);
  }
});

test('collections: cover can be a detail photo of a work; focus reaches the public copy', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener' });
  await addDetail('2026', 'rano', '1 Květy.jpg');
  await run(opts());
  const id = await idOf('2026', 'rano');
  await setCollection('plener', `title: Plenér\ncover: ${id}#1-kvety\nfocus: [30, 70]\n`);
  assert.equal((await run(opts())).ok, true);
  const copy = YAML.parse(await fs.readFile(path.join(siteDir, 'content/collections/plener.yaml'), 'utf8'));
  assert.deepEqual(copy, { title: 'Plenér', cover: `${id}#1-kvety`, focus: [30, 70] });

  await setCollection('plener', `title: Plenér\ncover: ${id}#lodka\n`);
  let r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /Ráno has no detail photo "lodka" \(folder tvorba\/plener\/rano\/\)/);

  await setCollection('plener', 'title: Plenér\nfocus: [50, 150]\n');
  r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /tvorba\/plener\/_kolekce\.yaml: focus must be \[x, y\]/);
});

test('collections: the share image is the cover cropped to 3:2 around focus, like the page', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener' });
  // panorama 90 × 30: left third red, middle green, right third blue
  const third = (c) => sharp({ create: { width: 30, height: 30, channels: 3, background: c } }).png().toBuffer();
  const panorama = await sharp({ create: { width: 90, height: 30, channels: 3, background: '#000' } })
    .composite([{ input: await third('#ff0000'), left: 0, top: 0 }, { input: await third('#00ff00'), left: 30, top: 0 }, { input: await third('#0000ff'), left: 60, top: 0 }])
    .jpeg({ quality: 100 }).toBuffer();
  await fs.writeFile(collFile('plener', '_uvod.jpg'), panorama);
  const og = path.join(siteDir, 'public/og/collections/plener.jpg');
  const dominant = async () => {
    // read the bytes: sharp caches files by path, the same path would return the old image
    const { channels } = await sharp(await fs.readFile(og)).stats();
    return channels.slice(0, 3).map((ch) => Math.round(ch.mean));
  };

  await setCollection('plener', 'title: Plenér\nfocus: [0, 50]\n');
  await run(opts());
  const { width, height } = await sharp(await fs.readFile(og)).metadata();
  assert.deepEqual([width, height], [config.images.og.width, config.images.og.height]);
  const [r, , b] = await dominant();
  assert.ok(r > 150 && b < 100, `left crop is mostly red: ${await dominant()}`);

  // unchanged input → the file is not rewritten
  const mtime = (await fs.stat(og)).mtimeMs;
  await run(opts());
  assert.equal((await fs.stat(og)).mtimeMs, mtime);

  await setCollection('plener', 'title: Plenér\nfocus: [100, 50]\n');
  await run(opts());
  const [r2, , b2] = await dominant();
  assert.ok(b2 > 150 && r2 < 100, `right crop is mostly blue: ${await dominant()}`);

  // collection gone → share image and the empty og folders are removed
  await fs.rm(path.join(contentDir, 'tvorba/plener'), { recursive: true });
  const r3 = await run(opts());
  assert.ok(r3.pruned.includes('public/og/collections/plener.jpg'));
  assert.ok(!(await exists(path.join(siteDir, 'public/og'))));
});

test('collections: without its own photo the share image comes from the cover work or detail', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener' });
  await addDetail('2026', 'rano', 'kvet.jpg', '#113355');
  await run(opts());
  await setCollection('plener', `title: Plenér\ncover: ${await idOf('2026', 'rano')}#kvet\n`);
  await run(opts());
  const { channels } = await sharp(path.join(siteDir, 'public/og/collections/plener.jpg')).stats();
  // the detail is #113355 (dark blue), the work master #88aacc (light blue)
  assert.ok(channels[2].mean < 110, `share image comes from the detail: ${channels.map((c) => Math.round(c.mean))}`);
});

test('share image: every work gets og.jpg, the whole work on paper in 3:2, listed in info.json', async () => {
  // a tall work (addWork makes wide masters)
  const dir = path.join(contentDir, 'tvorba');
  await fs.mkdir(dir, { recursive: true });
  await sharp({ create: { width: 300, height: 600, channels: 3, background: '#223344' } }).jpeg().toFile(path.join(dir, 'vysoky.jpg'));
  await fs.writeFile(path.join(dir, 'vysoky.yaml'), 'title: Vysoký\ndate: 2026-06-14\n');
  await run(opts());
  const info = await infoOf('2026', 'vysoky');
  const { width: W, height: H, background } = config.images.og;
  assert.deepEqual(info.og, { width: W, height: H });
  const file = path.join(await workDir('2026', 'vysoky'), 'og.jpg');
  const buf = await fs.readFile(file);
  const meta = await sharp(buf).metadata();
  assert.deepEqual([meta.width, meta.height], [W, H]);
  // not cropped: the sides are paper, the middle is the work
  const px = async (left, top) => [...(await sharp(buf).extract({ left, top, width: 1, height: 1 }).raw().toBuffer())];
  const paper = [1, 3, 5].map((i) => parseInt(background.slice(i, i + 2), 16));
  for (const [l, t] of [[5, 5], [W - 6, H - 6], [5, H / 2]]) {
    (await px(l, t)).forEach((v, i) => assert.ok(Math.abs(v - paper[i]) < 8, `paper at ${l},${t}: ${v} vs ${paper[i]}`));
  }
  const mid = await px(W / 2, H / 2);
  assert.ok(mid[2] < 100, `work in the middle: ${mid}`);
});

test('test data: the real content refuses test works, collections and photos; nothing is written', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addWork('2026', 'demo-kytice', 'title: Kytice\ndate: 2026-06-14\n');
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-14\ndemo: true\n');
  await setCollection('demo-plener', 'title: Plenér\n');
  await addPhoto('portret', 'alt: x\ndemo: true\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  const text = r.problems.join('\n');
  for (const where of ['tvorba/demo-kytice.yaml', 'tvorba/vecer.yaml', 'tvorba/demo-plener/_kolekce.yaml', 'fotky/portret.yaml']) {
    assert.match(text, new RegExp(`${where.replace(/[./]/g, '\\$&')}: test data do not belong in the real content`), where);
  }
  assert.ok(!text.includes('tvorba/rano.yaml'));
  assert.ok(!(await exists(path.join(siteDir, 'public/works'))));
});

test('test data: the demo data set accepts only marked items', async () => {
  await addWork('2026', 'demo-rano', 'title: Ráno\ndate: 2026-06-14\ndemo: true\n');
  assert.equal((await run(opts({ dataset: 'demo' }))).ok, true);
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-14\n');
  const r = await run(opts({ dataset: 'demo' }));
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /vecer\.yaml: every item of the test data needs "demo: true"/);
  assert.match(r.problems.join('\n'), /vecer\.yaml: names of test works and collections start with "demo-"/);
});

test('exports: Instagram only for works with instagram: true; switching it off removes the exports', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addDetail('2026', 'rano', 'kvet.jpg');
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-14\ninstagram: false\n');
  await addWork('2026', 'noc', 'title: Noc\ndate: 2026-06-14\ninstagram: true\n');
  await run(opts());
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), []);
  assert.deepEqual(await exportsOf('instagram', '2026', 'vecer'), []);
  assert.deepEqual(await exportsOf('instagram', '2026', 'noc'), ['-clean.jpg']);

  // switching it on regenerates the work with its details, switching it off removes the exports
  const id = await idOf('2026', 'rano');
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\ninstagram: true\n`);
  assert.equal((await run(opts())).processed, 1);
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), ['-clean.jpg', '-detail-kvet.jpg']);
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\n`);
  await run(opts());
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), []);
});

test('validation: instagram must be true or false', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ninstagram: ano\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /instagram must be true or false/);
});

test('prepare only (branches): skeletons, ids and checks, but no site data, images or exports', async () => {
  await addWork('2026', 'novy', undefined);
  await addWork('2026', 'hotovy', 'title: Hotový\ndate: 2026-06-14\ninstagram: true\n');
  const r = await run(opts({ prepareOnly: true, today: new Date('2026-05-01') }));
  assert.equal(r.ok, true);
  assert.equal(r.prepared, true);
  assert.deepEqual(r.created, ['tvorba/novy.yaml']);
  assert.equal(r.assigned.length, 1);
  const skeleton = YAML.parse(await fs.readFile(path.join(contentDir, 'tvorba/novy.yaml'), 'utf8'));
  assert.equal(skeleton.date, '2026-05-01', 'a new work is dated today');
  assert.equal(skeleton.draft, true);
  assert.equal(skeleton.title, 'Novy');
  assert.equal(skeleton.instagram, false);
  assert.ok(await idOf('2026', 'hotovy'));
  for (const p of ['content', 'public']) assert.ok(!(await exists(path.join(siteDir, p))), p);
  assert.ok(!(await exists(path.join(contentDir, 'export'))));

  // problems are reported as in a full run
  await setYaml('2026', 'hotovy', `id: ${await idOf('2026', 'hotovy')}\ntitle: Hotový\ndate: 2026-06-14\nstatus: available\n`);
  const bad = await run(opts({ prepareOnly: true }));
  assert.equal(bad.ok, false);
  assert.match(bad.problems.join('\n'), /needs a price/);
});

test('mockups: a master with surroundings (sheet box in XMP) is framed without them; the web image keeps them', async () => {
  // blue sheet with a magenta margin around it (a colour that no interior scene has), as `npm run straighten` produces with --margin
  const master = async (file, withBox) => {
    let img = sharp({ create: { width: 100, height: 80, channels: 3, background: '#ff00ff' } })
      .composite([{ input: await sharp({ create: { width: 80, height: 60, channels: 3, background: '#2040a0' } }).png().toBuffer(), left: 10, top: 10 }]);
    img = sharp(await img.png().toBuffer());
    if (withBox) img = img.withXmp(sheetXmp([0.1, 0.125, 0.9, 0.875]));
    await img.jpeg({ quality: 95 }).toFile(file);
  };
  const dir = path.join(contentDir, 'tvorba');
  await fs.mkdir(dir, { recursive: true });
  await master(path.join(dir, 'oriznuty.jpg'), true);
  await master(path.join(dir, 'celek.jpg'), false);
  for (const slug of ['oriznuty', 'celek']) {
    await fs.writeFile(path.join(dir, `${slug}.yaml`), `title: ${slug}\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n`);
  }
  assert.equal((await run(opts())).ok, true);
  // magenta pixels, also after the mockup's light and shadow: red and blue clearly above green
  const magenta = async (file) => {
    const { data } = await sharp(await fs.readFile(file)).raw().toBuffer({ resolveWithObject: true });
    let n = 0;
    for (let i = 0; i < data.length; i += 3) if (data[i] - data[i + 1] > 70 && data[i + 2] - data[i + 1] > 70) n++;
    return n;
  };
  const mockupFiles = async (slug) => {
    const d = await workDir('2026', slug);
    return (await fs.readdir(d)).filter((f) => f.startsWith('mockup-') && f.endsWith('.jpg')).map((f) => path.join(d, f));
  };
  assert.ok((await mockupFiles('oriznuty')).length > 0);
  for (const f of await mockupFiles('oriznuty')) assert.equal(await magenta(f), 0, `no margin in ${path.basename(f)}`);
  let control = 0;
  for (const f of await mockupFiles('celek')) control += await magenta(f);
  assert.ok(control > 0, 'without the box the margin is framed as part of the work');
  // the web image of the work keeps the surroundings
  assert.ok((await magenta(path.join(await workDir('2026', 'oriznuty'), '40.jpg'))) > 0);
});

test('skeletons contain every supported attribute (work, collection, photo) and pass the checks', async () => {
  await addWork('2026', 'novy', undefined, { collection: 'nova-kolekce' });
  await addPhoto('kontakt');
  const r = await run(opts({ today: new Date('2026-05-01') }));
  assert.equal(r.ok, true, r.problems.join('\n'));
  const keysOf = async (...p) => Object.keys(YAML.parse(await fs.readFile(path.join(contentDir, ...p), 'utf8')));
  const missing = (fields, keys) => fields.filter((f) => !keys.includes(f));
  // a new attribute must also go into the template in scripts/templates/, see WORK_FIELDS etc.
  assert.deepEqual(missing(WORK_FIELDS, await keysOf('tvorba/nova-kolekce/novy.yaml')), [], 'scripts/templates/work.yaml');
  assert.deepEqual(missing(COLLECTION_FIELDS, await keysOf('tvorba/nova-kolekce/_kolekce.yaml')), [], 'scripts/templates/collection.yaml');
  assert.deepEqual(missing(PHOTO_FIELDS, await keysOf('fotky/kontakt.yaml')), [], 'scripts/templates/photo.yaml');
});
