import { test, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import YAML from 'yaml';
import { run } from './process-images.mjs';

const siteConfig = YAML.parse(await fs.readFile(new URL('../site.config.yaml', import.meta.url), 'utf8'));
// Small web widths keep the test fast.
const config = {
  ...siteConfig,
  images: {
    ...siteConfig.images,
    web: { widths: [40, 80], quality: 70 },
    mockups: { widths: [60] },
    photos: { widths: [40] },
    fler: { ...siteConfig.images.fler, longEdge: 120 },
  },
};

let tmp, contentDir, siteDir;
const exists = (p) => fs.access(p).then(() => true, () => false);
const quiet = () => {};
const opts = (over = {}) => ({ contentDir, siteDir, config, log: quiet, ...over });

async function addWork(year, slug, yaml, { image = true } = {}) {
  const dir = path.join(contentDir, 'tvorba', year);
  await fs.mkdir(dir, { recursive: true });
  if (yaml !== undefined) await fs.writeFile(path.join(dir, `${slug}.yaml`), yaml);
  if (image) {
    await sharp({ create: { width: 64, height: 48, channels: 3, background: '#88aacc' } }).jpeg().toFile(path.join(dir, `${slug}.jpg`));
  }
}
const idOf = async (year, slug) => YAML.parse(await fs.readFile(path.join(contentDir, 'tvorba', year, `${slug}.yaml`), 'utf8')).id;

beforeEach(async () => {
  tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'pavla-pipeline-'));
  contentDir = path.join(tmp, 'pavla-content');
  siteDir = path.join(tmp, 'pavla');
  await fs.mkdir(path.join(contentDir, 'tvorba'), { recursive: true });
  await fs.mkdir(siteDir);
});
afterEach(() => fs.rm(tmp, { recursive: true, force: true }));

test('generates web images, metadata copy and exports under <year>/<slug>-<id>', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nsize_cm: [40, 30]\n');
  const r = await run(opts());
  assert.equal(r.ok, true);
  assert.equal(r.processed, 1);
  const key = `rano-${await idOf('2026', 'rano')}`;

  const info = JSON.parse(await fs.readFile(path.join(siteDir, 'public/works/2026', key, 'info.json'), 'utf8'));
  // The master is 64 px wide: 40 fits, 80 would upscale, so the full width is added instead.
  assert.deepEqual(info.widths, [40, 64]);
  for (const f of ['40.avif', '40.webp', '40.jpg', '64.jpg']) assert.ok(await exists(path.join(siteDir, 'public/works/2026', key, f)), f);

  const copy = await fs.readFile(path.join(siteDir, 'content/works/2026', `${key}.yaml`), 'utf8');
  assert.match(copy, /^# Generated by/);
  assert.equal(YAML.parse(copy).title, 'Ráno');

  for (const f of [`instagram/2026/${key}-clean.jpg`, `instagram/2026/${key}-wall.jpg`, `fler/2026/${key}.jpg`]) {
    assert.ok(await exists(path.join(contentDir, 'export', f)), f);
  }
});

test('second run skips unchanged works; --force regenerates', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  const again = await run(opts());
  assert.equal(again.processed, 0);
  assert.equal(again.skipped, 1);
  const forced = await run(opts({ force: true }));
  assert.equal(forced.processed, 1);
});

test('a new image without metadata becomes a draft with generated outputs', async () => {
  await addWork('2026', 'novy', undefined);
  const r = await run(opts({ today: new Date('2026-05-01') }));
  assert.deepEqual(r.created, ['2026/novy.yaml']);
  const key = `novy-${await idOf('2026', 'novy')}`;
  assert.equal(YAML.parse(await fs.readFile(path.join(siteDir, 'content/works/2026', `${key}.yaml`), 'utf8')).draft, true);
  assert.ok(await exists(path.join(siteDir, 'public/works/2026', key, 'info.json')));
});

test('renaming a work keeps its id and removes the old outputs', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const dir = path.join(contentDir, 'tvorba/2026');
  await fs.rename(path.join(dir, 'rano.yaml'), path.join(dir, 'rano-u-rybnika.yaml'));
  await fs.rename(path.join(dir, 'rano.jpg'), path.join(dir, 'rano-u-rybnika.jpg'));

  const r = await run(opts());
  assert.deepEqual(r.pruned.sort(), [`content/works/2026/rano-${id}.yaml`, `public/works/2026/rano-${id}/`]);
  assert.ok(await exists(path.join(siteDir, 'public/works/2026', `rano-u-rybnika-${id}`, 'info.json')));
  assert.ok(!(await exists(path.join(siteDir, 'public/works/2026', `rano-${id}`))));
});

test('deleting the last work of a year removes the empty year folders', async () => {
  await addWork('2025', 'stary', 'title: Starý\ndate: 2025-03-01\n');
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  await fs.rm(path.join(contentDir, 'tvorba/2025'), { recursive: true });
  await run(opts());
  assert.ok(!(await exists(path.join(siteDir, 'public/works/2025'))));
  assert.ok(!(await exists(path.join(siteDir, 'content/works/2025'))));
});

test('a work without master keeps existing outputs and reports missing ones', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  await fs.rm(path.join(contentDir, 'tvorba/2026/rano.jpg'));
  const kept = await run(opts());
  assert.equal(kept.ok, true);
  assert.deepEqual(kept.pruned, []);

  await addWork('2026', 'bez-fotky', 'title: Bez fotky\ndate: 2026-01-01\n', { image: false });
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.deepEqual(r.missing, [`2026/bez-fotky-${await idOf('2026', 'bez-fotky')}`]);
});

test('validation problems stop the run before anything is written to the site', async () => {
  await addWork('2026', 'spatny-rok', 'title: Špatný rok\ndate: 2025-06-14\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems[0], /does not match year folder 2026/);
  assert.ok(!(await exists(path.join(siteDir, 'public/works'))));
  assert.ok(!(await exists(path.join(siteDir, 'content/works'))));
});

test('only=<slug> processes one work and never prunes', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-15\n');
  const r = await run(opts({ only: ['vecer'] }));
  assert.equal(r.processed, 1);
  assert.ok(!(await exists(path.join(siteDir, 'public/works/2026', `rano-${await idOf('2026', 'rano')}`))));
});

test('refuses to prune when the content repository has no works', async () => {
  await assert.rejects(run(opts()), /No works found/);
});

test('fails clearly when the content repository is missing', async () => {
  await assert.rejects(run(opts({ contentDir: path.join(tmp, 'nothing') })), /Content not found/);
});

const infoOf = async (year, slug) =>
  JSON.parse(await fs.readFile(path.join(siteDir, 'public/works', year, `${slug}-${await idOf(year, slug)}`, 'info.json'), 'utf8'));
const setYaml = (year, slug, text) => fs.writeFile(path.join(contentDir, 'tvorba', year, `${slug}.yaml`), text);

test('generates three mockups and lists them in info.json', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nsize_cm: [40, 30]\n');
  await run(opts());
  const info = await infoOf('2026', 'rano');
  assert.equal(info.mockups.length, 3);
  assert.equal(new Set(info.mockups.map((m) => m.scene)).size, 3);
  const dir = path.join(siteDir, 'public/works/2026', `rano-${await idOf('2026', 'rano')}`);
  for (const m of info.mockups) {
    assert.ok(m.label);
    for (const ext of ['avif', 'webp', 'jpg']) assert.ok(await exists(path.join(dir, `mockup-${m.scene}-60.${ext}`)), `${m.scene} ${ext}`);
  }
});

test('changing size_cm regenerates the work, changing the price does not', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nsize_cm: [40, 30]\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const before = (await infoOf('2026', 'rano')).fingerprint;

  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nsize_cm: [40, 30]\nprice: 3200\n`);
  assert.equal((await run(opts())).processed, 0);

  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nsize_cm: [20, 15]\nprice: 3200\n`);
  const r = await run(opts());
  assert.equal(r.processed, 1);
  const after = await infoOf('2026', 'rano');
  assert.notEqual(after.fingerprint, before);
  // A 20 × 15 cm work is small: shelf and desk instead of living room and hallway.
  assert.deepEqual(after.mockups.slice(1).map((m) => m.scene), ['police', 'pracovna']);
});

test('regeneration removes mockups of scenes that are no longer picked', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nsize_cm: [56, 38]\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const dir = path.join(siteDir, 'public/works/2026', `rano-${id}`);
  const old = (await infoOf('2026', 'rano')).mockups.map((m) => m.scene);
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nsize_cm: [20, 15]\n`);
  await run(opts());
  const now = (await infoOf('2026', 'rano')).mockups.map((m) => m.scene);
  for (const scene of old.filter((s) => !now.includes(s))) {
    assert.ok(!(await exists(path.join(dir, `mockup-${scene}-60.jpg`))), scene);
  }
});

async function addPhoto(name, yaml) {
  const dir = path.join(contentDir, 'fotky');
  await fs.mkdir(dir, { recursive: true });
  await sharp({ create: { width: 50, height: 70, channels: 3, background: '#c9b79c' } }).jpeg().toFile(path.join(dir, `${name}.jpg`));
  if (yaml !== undefined) await fs.writeFile(path.join(dir, `${name}.yaml`), yaml);
}

test('photos: a new photo gets a skeleton description and web sizes', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addPhoto('portret');
  const r = await run(opts());
  assert.ok(r.created.includes('fotky/portret.yaml'));
  const info = JSON.parse(await fs.readFile(path.join(siteDir, 'public/photos/portret/info.json'), 'utf8'));
  assert.equal(info.alt, 'Portret');
  assert.deepEqual(info.widths, [40]);
  assert.ok(await exists(path.join(siteDir, 'public/photos/portret/40.avif')));
});

test('photos: editing the description updates info.json, deleting the photo removes it', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addPhoto('atelier', 'alt: Ateliér\ncaption: Kde maluji\n');
  await run(opts());
  await fs.writeFile(path.join(contentDir, 'fotky/atelier.yaml'), 'alt: Ateliér u okna\ncaption: Kde maluji\n');
  await run(opts());
  const info = JSON.parse(await fs.readFile(path.join(siteDir, 'public/photos/atelier/info.json'), 'utf8'));
  assert.equal(info.alt, 'Ateliér u okna');

  await fs.rm(path.join(contentDir, 'fotky/atelier.jpg'));
  await fs.rm(path.join(contentDir, 'fotky/atelier.yaml'));
  const r = await run(opts());
  assert.ok(r.pruned.includes('public/photos/atelier/'));
  assert.ok(!(await exists(path.join(siteDir, 'public/photos/atelier'))));
});

test('photos: a description without a photo is reported', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await fs.mkdir(path.join(contentDir, 'fotky'));
  await fs.writeFile(path.join(contentDir, 'fotky/sirotek.yaml'), 'alt: x\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems[0], /no photo named "sirotek"/);
});

test('the Instagram wall export is a 4:5 mockup', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nsize_cm: [40, 30]\n');
  await run(opts());
  const file = path.join(contentDir, 'export/instagram/2026', `rano-${await idOf('2026', 'rano')}-wall.jpg`);
  const { width, height } = await sharp(file).metadata();
  assert.deepEqual([width, height], [config.images.instagram.width, config.images.instagram.height]);
});
