import { test, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import YAML from 'yaml';
import { run } from './process-images.mjs';
import { sheetXmp } from './lib/sheet-box.mjs';
import { WORK_FIELDS } from './lib/works.mjs';
import { COLLECTION_FIELDS } from './lib/collections.mjs';
import { WORK_SCHEMA } from './lib/schema.mjs';
import { PHOTO_FIELDS } from './lib/photos.mjs';

const siteConfig = YAML.parse(await fs.readFile(new URL('../site.config.yaml', import.meta.url), 'utf8'));
// Small web widths keep the test fast.
const config = {
  ...siteConfig,
  images: {
    ...siteConfig.images,
    web: { widths: [40, 80], quality: 70 },
    mockups: { widths: [60] },
    details: { widths: [30] },
    photos: { widths: [40] },
    fler: { ...siteConfig.images.fler, longEdge: 120 },
  },
};

let tmp, contentDir, siteDir;
const exists = (p) => fs.access(p).then(() => true, () => false);
const quiet = () => {};
const opts = (over = {}) => ({ contentDir, siteDir, config, log: quiet, ...over });

// The content repository has no year folders: `year` only documents the date of the work.
async function addWork(year, slug, yaml, { image = true, collection = '' } = {}) {
  const dir = path.join(contentDir, 'tvorba', collection);
  await fs.mkdir(dir, { recursive: true });
  if (yaml !== undefined) await fs.writeFile(path.join(dir, `${slug}.yaml`), yaml);
  if (image) {
    await sharp({ create: { width: 64, height: 48, channels: 3, background: '#88aacc' } }).jpeg().toFile(path.join(dir, `${slug}.jpg`));
  }
}
/** Folder of the work with this slug: tvorba/ or its collection folder. */
async function workFolder(slug) {
  const root = path.join(contentDir, 'tvorba');
  if (await exists(path.join(root, `${slug}.yaml`))) return root;
  for (const e of await fs.readdir(root, { withFileTypes: true })) {
    if (e.isDirectory() && (await exists(path.join(root, e.name, `${slug}.yaml`)))) return path.join(root, e.name);
  }
  return root;
}
const idOf = async (year, slug) => YAML.parse(await fs.readFile(path.join(await workFolder(slug), `${slug}.yaml`), 'utf8')).id;

beforeEach(async () => {
  tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'pavla-pipeline-'));
  contentDir = path.join(tmp, 'content');
  siteDir = path.join(tmp, 'pavla');
  await fs.mkdir(path.join(contentDir, 'tvorba'), { recursive: true });
  await fs.mkdir(siteDir);
});
afterEach(() => fs.rm(tmp, { recursive: true, force: true }));

test('generates web images, metadata copy and exports under <year>/<slug>-<id>', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmeta_instagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  const r = await run(opts());
  assert.equal(r.ok, true);
  assert.equal(r.processed, 1);
  const key = `rano-${await idOf('2026', 'rano')}`;

  const info = JSON.parse(await fs.readFile(path.join(siteDir, 'public/tvorba/2026', key, 'info.json'), 'utf8'));
  // The master is 64 px wide: 40 fits, 80 would upscale, so the full width is added instead.
  assert.deepEqual(info.widths, [40, 64]);
  for (const f of ['40.avif', '40.webp', '40.jpg', '64.jpg']) assert.ok(await exists(path.join(siteDir, 'public/tvorba/2026', key, f)), f);

  // the public copy lies where the description lies in the content repository
  const copy = await fs.readFile(path.join(siteDir, 'content/tvorba/rano.yaml'), 'utf8');
  assert.match(copy, /^# Generated by/);
  assert.equal(YAML.parse(copy).title, 'Ráno');

  for (const f of [`instagram/2026/${key}-clean.jpg`, `fler/2026/${key}.jpg`, `fler/2026/${key}-mockup-${info.mockups[0].scene}.jpg`]) {
    assert.ok(await exists(path.join(contentDir, 'export', f)), f);
  }
});

test('second run skips unchanged works; --force regenerates', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  const again = await run(opts());
  assert.equal(again.processed, 0);
  assert.equal(again.skipped, 1);
  const forced = await run(opts({ force: true }));
  assert.equal(forced.processed, 1);
});

test('a new image without metadata becomes a draft that never leaves the content repository', async () => {
  await addWork('2026', 'novy', undefined);
  const r = await run(opts({ today: new Date('2026-05-01') }));
  assert.equal(r.ok, true);
  assert.deepEqual(r.created, ['tvorba/novy.yaml', 'roky/2026.yaml', '_index.yaml']);
  assert.equal(YAML.parse(await fs.readFile(path.join(contentDir, 'tvorba/novy.yaml'), 'utf8')).meta_draft, true);
  assert.equal(r.processed, 0);
  assert.deepEqual(r.missing, []);
  assert.equal(await exists(path.join(siteDir, 'content/tvorba')), false);
  assert.equal(await exists(path.join(siteDir, 'public/tvorba')), false);
});

test('a draft gets no outputs; turning a published work back into a draft removes them all', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmeta_instagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\n');
  await addWork('2026', 'skica', 'title: Skica\ndate: 2026-06-20\nmeta_draft: true\nmeta_instagram: true\nstatus: available\nprice: 900\n');
  const r = await run(opts());
  assert.equal(r.ok, true);
  assert.equal(r.processed, 1, 'only the published work is processed');
  const id = await idOf('2026', 'rano');
  const skica = `skica-${await idOf('2026', 'skica')}`;
  assert.equal(await exists(path.join(siteDir, 'content/tvorba/skica.yaml')), false);
  assert.equal(await exists(path.join(siteDir, 'public/tvorba/2026', skica)), false);
  assert.equal(await exists(path.join(contentDir, 'export/instagram/2026', `${skica}-clean.jpg`)), false);
  assert.equal(await exists(path.join(contentDir, 'export/fler/2026', `${skica}.jpg`)), false);
  // the public copy of a published work has no draft attribute
  const copy = YAML.parse(await fs.readFile(path.join(siteDir, 'content/tvorba/rano.yaml'), 'utf8'));
  assert.equal('meta_draft' in copy, false);

  const rano = path.join(contentDir, 'tvorba/rano.yaml');
  await fs.writeFile(rano, (await fs.readFile(rano, 'utf8')).replace('meta_draft: false', 'meta_draft: true'));
  const again = await run(opts());
  assert.deepEqual(again.pruned.sort(), [
    'content/tvorba/rano.yaml', `export/fler/2026/rano-${id}.jpg`,
    `export/instagram/2026/rano-${id}-clean.jpg`, `public/tvorba/2026/rano-${id}/`,
  ]);
  assert.equal(await exists(path.join(siteDir, 'content/tvorba')), false, 'empty folders are removed too');
  // idempotent: nothing left to remove
  assert.deepEqual((await run(opts())).pruned, []);
});

test('renaming a work keeps its id and removes the old outputs', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmeta_instagram: true\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const dir = path.join(contentDir, 'tvorba');
  await fs.rename(path.join(dir, 'rano.yaml'), path.join(dir, 'rano-u-rybnika.yaml'));
  await fs.rename(path.join(dir, 'rano.jpg'), path.join(dir, 'rano-u-rybnika.jpg'));

  const r = await run(opts());
  assert.deepEqual(r.pruned.sort(), [
    'content/tvorba/rano.yaml', `export/instagram/2026/rano-${id}-clean.jpg`, `public/tvorba/2026/rano-${id}/`,
  ]);
  assert.ok(await exists(path.join(siteDir, 'content/tvorba/rano-u-rybnika.yaml')));
  assert.ok(await exists(path.join(siteDir, 'public/tvorba/2026', `rano-u-rybnika-${id}`, 'info.json')));
  assert.ok(!(await exists(path.join(siteDir, 'public/tvorba/2026', `rano-${id}`))));
});

test('deleting the last work of a year removes the empty year folders', async () => {
  await addWork('2025', 'stary', 'title: Starý\ndate: 2025-03-01\n');
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  for (const f of ['stary.yaml', 'stary.jpg']) await fs.rm(path.join(contentDir, 'tvorba', f));
  await run(opts());
  assert.ok(!(await exists(path.join(siteDir, 'public/tvorba/2025'))));
  assert.ok(!(await exists(path.join(siteDir, 'content/tvorba/stary.yaml'))));
});

test('a work without master keeps existing outputs and reports missing ones', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  await fs.rm(path.join(contentDir, 'tvorba/rano.jpg'));
  const kept = await run(opts());
  assert.equal(kept.ok, true);
  assert.deepEqual(kept.pruned, []);

  await addWork('2026', 'bez-fotky', 'title: Bez fotky\ndate: 2026-01-01\n', { image: false });
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.deepEqual(r.missing, [`2026/bez-fotky-${await idOf('2026', 'bez-fotky')}`]);
});

test('validation problems stop the run before anything is written to the site', async () => {
  await addWork('2026', 'spatne-datum', 'title: Špatné datum\ndate: 14. 6. 2026\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems[0], /tvorba\/spatne-datum\.yaml: date must be a day like 2026-06-14/);
  assert.ok(!(await exists(path.join(siteDir, 'public/tvorba'))));
  assert.ok(!(await exists(path.join(siteDir, 'content'))));
});

test('only=<slug> processes one work and never prunes', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-15\n');
  const r = await run(opts({ only: ['vecer'] }));
  assert.equal(r.processed, 1);
  assert.ok(!(await exists(path.join(siteDir, 'public/tvorba/2026', `rano-${await idOf('2026', 'rano')}`))));
});

test('no works (before the first real work) is fine and removes all generated works', async () => {
  assert.equal((await run(opts())).ok, true);
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  for (const f of ['rano.yaml', 'rano.jpg']) await fs.rm(path.join(contentDir, 'tvorba', f));
  const r = await run(opts());
  assert.equal(r.ok, true);
  assert.ok(!(await exists(path.join(siteDir, 'public/tvorba/2026'))));
  assert.ok(!(await exists(path.join(siteDir, 'content/tvorba'))));
});

test('fails clearly when the content repository is missing', async () => {
  await assert.rejects(run(opts({ contentDir: path.join(tmp, 'nothing') })), /Content not found/);
});

const infoOf = async (year, slug) =>
  JSON.parse(await fs.readFile(path.join(siteDir, 'public/tvorba', year, `${slug}-${await idOf(year, slug)}`, 'info.json'), 'utf8'));
const setYaml = async (year, slug, text) => fs.writeFile(path.join(await workFolder(slug), `${slug}.yaml`), text);

test('generates three mockups and lists them in info.json', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const info = await infoOf('2026', 'rano');
  assert.equal(info.mockups.length, 3);
  assert.equal(new Set(info.mockups.map((m) => m.scene)).size, 3);
  const dir = path.join(siteDir, 'public/tvorba/2026', `rano-${await idOf('2026', 'rano')}`);
  for (const m of info.mockups) {
    assert.ok(m.label);
    for (const ext of ['avif', 'webp', 'jpg']) assert.ok(await exists(path.join(dir, `mockup-${m.scene}-60.${ext}`)), `${m.scene} ${ext}`);
  }
});

test('changing size_cm regenerates the work, changing the price does not', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const before = (await infoOf('2026', 'rano')).fingerprint;

  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nstatus: available\nsize_cm: [40, 30]\nmockups: true\nprice: 3200\n`);
  assert.equal((await run(opts())).processed, 0);

  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nstatus: available\nsize_cm: [20, 15]\nmockups: true\nprice: 3200\n`);
  const r = await run(opts());
  assert.equal(r.processed, 1);
  const after = await infoOf('2026', 'rano');
  assert.notEqual(after.fingerprint, before);
  // A 20 × 15 cm work is small: shelf and desk instead of living room and hallway.
  assert.deepEqual(after.mockups.slice(1).map((m) => m.scene), ['police', 'pracovna']);
});

test('regeneration removes mockups of scenes that are no longer picked', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [56, 38]\nmockups: true\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const dir = path.join(siteDir, 'public/tvorba/2026', `rano-${id}`);
  const old = (await infoOf('2026', 'rano')).mockups.map((m) => m.scene);
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [20, 15]\nmockups: true\n`);
  await run(opts());
  const now = (await infoOf('2026', 'rano')).mockups.map((m) => m.scene);
  for (const scene of old.filter((s) => !now.includes(s))) {
    assert.ok(!(await exists(path.join(dir, `mockup-${scene}-60.jpg`))), scene);
  }
});

async function addPhoto(name, yaml) {
  const dir = path.join(contentDir, 'fotky');
  await fs.mkdir(dir, { recursive: true });
  await sharp({ create: { width: 50, height: 70, channels: 3, background: '#c9b79c' } }).jpeg().toFile(path.join(dir, `${name}.jpg`));
  if (yaml !== undefined) await fs.writeFile(path.join(dir, `${name}.yaml`), yaml);
}

test('photos: a new photo gets a skeleton description and web sizes', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addPhoto('portret');
  const r = await run(opts());
  assert.ok(r.created.includes('fotky/portret.yaml'));
  const info = JSON.parse(await fs.readFile(path.join(siteDir, 'public/fotky/portret/info.json'), 'utf8'));
  assert.deepEqual(info.widths, [40]);
  assert.equal(info.alt, undefined, 'info.json holds only image data');
  // the description goes to its public copy, like every other one
  assert.equal(YAML.parse(await fs.readFile(path.join(siteDir, 'content/fotky/portret.yaml'), 'utf8')).alt, 'Portret');
  assert.ok(await exists(path.join(siteDir, 'public/fotky/portret/40.avif')));
});

test('photos: editing the description updates its public copy, deleting the photo removes both', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addPhoto('atelier', 'alt: Ateliér\ncaption: Kde maluji\n');
  await run(opts());
  await fs.writeFile(path.join(contentDir, 'fotky/atelier.yaml'), 'alt: Ateliér u okna\ncaption: Kde maluji\n');
  await run(opts());
  const copy = YAML.parse(await fs.readFile(path.join(siteDir, 'content/fotky/atelier.yaml'), 'utf8'));
  assert.deepEqual(copy, { alt: 'Ateliér u okna', caption: 'Kde maluji', focus: [50, 50] });

  await fs.rm(path.join(contentDir, 'fotky/atelier.jpg'));
  await fs.rm(path.join(contentDir, 'fotky/atelier.yaml'));
  const r = await run(opts());
  assert.ok(r.pruned.includes('public/fotky/atelier/'));
  assert.ok(r.pruned.includes('content/fotky/atelier.yaml'));
  assert.ok(!(await exists(path.join(siteDir, 'public/fotky/atelier'))));
});

test('photos: a description without a photo is reported', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await fs.mkdir(path.join(contentDir, 'fotky'));
  await fs.writeFile(path.join(contentDir, 'fotky/sirotek.yaml'), 'alt: x\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems[0], /no photo named "sirotek"/);
});


const workDir = async (year, slug) => path.join(siteDir, 'public/tvorba', year, `${slug}-${await idOf(year, slug)}`);
/** Export file names of a work on one platform (instagram | fler), without the "<key>" prefix. */
const exportsOf = async (sub, year, slug) => {
  const key = `${slug}-${await idOf(year, slug)}`;
  const dir = path.join(contentDir, 'export', sub, year);
  if (!(await exists(dir))) return [];
  return (await fs.readdir(dir)).filter((f) => f.startsWith(key)).map((f) => f.slice(key.length)).sort();
};

test('mockups: only works with mockups: true get them, whatever their status', async () => {
  const yaml = (title, status, extra) => `title: ${title}\ndate: 2026-06-14\nstatus: ${status}\n${status === 'available' || status === 'reserved' ? 'price: 1000\n' : ''}size_cm: [40, 30]\n${extra}`;
  await addWork('2026', 'volny', yaml('Volný', 'available', 'mockups: true\n'));
  await addWork('2026', 'volny-bez', yaml('Volný bez', 'available', 'mockups: false\n'));
  await addWork('2026', 'doma', yaml('Doma', 'not-for-sale', 'mockups: true\n'));
  await addWork('2026', 'prodany', yaml('Prodaný', 'sold', 'mockups: true\n'));
  await addWork('2026', 'bez-pole', yaml('Bez pole', 'reserved', ''));
  assert.equal((await run(opts())).ok, true);
  for (const slug of ['volny', 'doma', 'prodany']) assert.equal((await infoOf('2026', slug)).mockups.length, 3, slug);
  for (const slug of ['volny-bez', 'bez-pole']) {
    assert.deepEqual((await infoOf('2026', slug)).mockups, [], slug);
    assert.ok(!(await fs.readdir(await workDir('2026', slug))).some((f) => f.startsWith('mockup-')), slug);
  }
  // Fler follows the status: works on sale get the original and their mockups, others nothing
  assert.equal((await exportsOf('fler', '2026', 'volny')).length, 4);
  assert.deepEqual(await exportsOf('fler', '2026', 'volny-bez'), ['.jpg']);
  assert.deepEqual(await exportsOf('fler', '2026', 'bez-pole'), ['.jpg']);
  for (const slug of ['doma', 'prodany']) assert.deepEqual(await exportsOf('fler', '2026', slug), [], slug);
  // the public copy carries the flag, the page reads it
  const copy = YAML.parse(await fs.readFile(path.join(siteDir, 'content/tvorba/doma.yaml'), 'utf8'));
  assert.equal(copy.mockups, true);
});

test('mockups: selling a work removes its Fler exports but keeps its mockups; mockups: false removes them', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmeta_instagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  assert.equal((await infoOf('2026', 'rano')).mockups.length, 3);
  assert.equal((await exportsOf('fler', '2026', 'rano')).length, 4);

  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nmeta_instagram: true\nstatus: sold\nsize_cm: [40, 30]\nmockups: true\n`);
  assert.equal((await run(opts())).processed, 1);
  assert.equal((await infoOf('2026', 'rano')).mockups.length, 3, 'a sold work keeps its mockups');
  assert.deepEqual(await exportsOf('fler', '2026', 'rano'), []);
  assert.ok(await exists(path.join(contentDir, 'export/instagram/2026', `rano-${id}-clean.jpg`)));

  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nmeta_instagram: true\nstatus: sold\nsize_cm: [40, 30]\nmockups: false\n`);
  assert.equal((await run(opts())).processed, 1);
  assert.deepEqual((await infoOf('2026', 'rano')).mockups, []);
  assert.ok(!(await fs.readdir(await workDir('2026', 'rano'))).some((f) => f.startsWith('mockup-')));

  // available → reserved changes nothing that is generated
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n`);
  await run(opts());
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nstatus: reserved\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n`);
  assert.equal((await run(opts())).processed, 0);
});

test('validation: mockups must be true or false', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmockups: ano\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /mockups must be true or false/);
});

async function addDetail(year, slug, file, color = '#aa6644') {
  const dir = path.join(await workFolder(slug), slug);
  await fs.mkdir(dir, { recursive: true });
  await sharp({ create: { width: 40, height: 40, channels: 3, background: color } }).jpeg().toFile(path.join(dir, file));
}

test('details: detail photos get web sizes and are listed in info.json in file name order', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addDetail('2026', 'rano', '2-lodka.jpg');
  await addDetail('2026', 'rano', '1 Květ.jpg');
  assert.equal((await run(opts())).ok, true);
  const info = await infoOf('2026', 'rano');
  assert.deepEqual(info.details.map((d) => d.name), ['1-kvet', '2-lodka']);
  assert.deepEqual(info.details[0].widths, [30]);
  for (const ext of ['avif', 'webp', 'jpg']) assert.ok(await exists(path.join(await workDir('2026', 'rano'), `detail-1-kvet-30.${ext}`)), ext);
});

test('details: adding, changing or removing a detail photo regenerates the work', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await run(opts());
  assert.deepEqual((await infoOf('2026', 'rano')).details, []);

  await addDetail('2026', 'rano', 'kvet.jpg');
  assert.equal((await run(opts())).processed, 1);
  assert.equal((await run(opts())).processed, 0);

  await addDetail('2026', 'rano', 'kvet.jpg', '#113355');
  assert.equal((await run(opts())).processed, 1);

  await fs.rm(path.join(contentDir, 'tvorba/rano'), { recursive: true });
  assert.equal((await run(opts())).processed, 1);
  assert.deepEqual((await infoOf('2026', 'rano')).details, []);
  assert.ok(!(await fs.readdir(await workDir('2026', 'rano'))).some((f) => f.startsWith('detail-')));
});

test('private note: never reaches the site repository, not even through comments', async () => {
  await addWork('2026', 'rano', [
    '# koupila teta, nikomu neříkat',
    'title: Ráno',
    'date: 2026-06-14',
    'description: Veřejný popis.',
    'private_note: |',
    '  Soukromá poznámka.',
    'poznamka: vymyšlené pole',
    '',
  ].join('\n'));
  await run(opts());
  const key = `rano-${await idOf('2026', 'rano')}`;
  const copy = await fs.readFile(path.join(siteDir, 'content/tvorba/rano.yaml'), 'utf8');
  assert.doesNotMatch(copy, /Soukromá|private_note|teta|vymyšlené/);
  // attributes the file lacked were added with values that mean the same as their absence
  const { derived_modified: modified, ...publicAttributes } = YAML.parse(copy);
  assert.deepEqual(publicAttributes, {
    id: key.slice(-5), title: 'Ráno', date: '2026-06-14', technique: '', size_cm: null, tags: [],
    status: 'not-for-sale', featured: false, description: 'Veřejný popis.', mockups: false,
  });
  assert.match(modified, /^\d{4}-\d{2}-\d{2}$/, 'the only other attribute is the derived day of the last change');
  // the private repository keeps the note
  assert.match(await fs.readFile(path.join(contentDir, 'tvorba/rano.yaml'), 'utf8'), /Soukromá poznámka/);
});

/** A file of a collection folder (tvorba/<collection>/). */
const collFile = (coll, name) => path.join(contentDir, 'tvorba', coll, name);
const setCollection = async (coll, text) => {
  await fs.mkdir(path.join(contentDir, 'tvorba', coll), { recursive: true });
  await fs.writeFile(collFile(coll, '_index.yaml'), text);
};
async function addCover(coll) {
  await fs.mkdir(path.join(contentDir, 'tvorba', coll), { recursive: true });
  await sharp({ create: { width: 60, height: 40, channels: 3, background: '#557744' } }).jpeg().toFile(collFile(coll, '_cover.jpg'));
}

test('collections: a folder in tvorba/ is a collection, gets a skeleton titled after it and a public copy', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: '2026-plener-sumava' });
  await addWork('2025', 'kvet', 'title: Květ\ndate: 2025-05-01\n', { collection: '2025 Jaro na zahradě' });
  await addWork('2026', 'sam', 'title: Sám\ndate: 2026-01-01\n');
  const r = await run(opts());
  assert.equal(r.ok, true, r.problems.join('\n'));
  assert.ok(r.created.includes('tvorba/2026-plener-sumava/_index.yaml'));
  // a leading year moves to the end of the title, the slug comes from the folder name
  assert.equal(YAML.parse(await fs.readFile(collFile('2026-plener-sumava', '_index.yaml'), 'utf8')).title, 'Plener sumava 2026');
  assert.equal(YAML.parse(await fs.readFile(collFile('2025 Jaro na zahradě', '_index.yaml'), 'utf8')).title, 'Jaro na zahradě 2025');
  // the public copy of a collection: _index.yaml in a folder named by its slug
  assert.ok(await exists(path.join(siteDir, 'content/tvorba/2025-jaro-na-zahrade/_index.yaml')));
  // a work lies in the folder of its collection, as in the content repository; no collection attribute
  const rano = YAML.parse(await fs.readFile(path.join(siteDir, 'content/tvorba/2026-plener-sumava/rano.yaml'), 'utf8'));
  assert.equal(rano.collection, undefined);
  assert.ok(await exists(path.join(siteDir, 'content/tvorba/2025-jaro-na-zahrade/kvet.yaml')));
  assert.ok(await exists(path.join(siteDir, 'content/tvorba/sam.yaml')));

  await setCollection('2026-plener-sumava', 'title: Plenér Šumava 2026\ndescription: Týden na Kvildě.\nprivate_note: tajné\n');
  await run(opts());
  const copy = await fs.readFile(path.join(siteDir, 'content/tvorba/2026-plener-sumava/_index.yaml'), 'utf8');
  assert.deepEqual(YAML.parse(copy), { title: 'Plenér Šumava 2026', description: 'Týden na Kvildě.' });
  assert.doesNotMatch(copy, /tajné/);
  // no cover photo, no cover folder
  assert.ok(!(await exists(path.join(siteDir, 'public/tvorba/kolekce/2026-plener-sumava/_cover'))));
});

test('collections: a collection may span years, its works keep their own years', async () => {
  await addWork('2025', 'prosinec', 'title: Prosinec\ndate: 2025-12-30\n', { collection: '2025-2026-zima' });
  await addWork('2026', 'leden', 'title: Leden\ndate: 2026-01-02\n', { collection: '2025-2026-zima' });
  assert.equal((await run(opts())).ok, true);
  assert.equal(YAML.parse(await fs.readFile(collFile('2025-2026-zima', '_index.yaml'), 'utf8')).title, 'Zima 2025–2026');
  // the copies stay in the collection folder; the images go by the year of each work
  assert.ok(await exists(path.join(siteDir, 'content/tvorba/2025-2026-zima/prosinec.yaml')));
  assert.ok(await exists(path.join(siteDir, 'public/tvorba/2025', `prosinec-${await idOf('2025', 'prosinec')}`, 'info.json')));
  assert.ok(await exists(path.join(siteDir, 'public/tvorba/2026', `leden-${await idOf('2026', 'leden')}`, 'info.json')));
});

test('collections: the former names _kolekce.yaml and _uvod.jpg are refused, no skeleton is written next to them', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener' });
  await fs.writeFile(collFile('plener', '_kolekce.yaml'), 'title: Můj plenér\n');
  await sharp({ create: { width: 60, height: 40, channels: 3, background: '#557744' } }).jpeg().toFile(collFile('plener', '_uvod.jpg'));
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.deepEqual(r.problems.filter((p) => p.includes('renamed')), [
    'tvorba/plener/_kolekce.yaml: renamed to _index.yaml, rename the file',
    'tvorba/plener/_uvod.jpg: renamed to _cover.jpg, rename the file',
  ]);
  assert.equal(await exists(collFile('plener', '_index.yaml')), false, 'no skeleton hides the old description');
  assert.equal(await exists(path.join(siteDir, 'content')), false, 'nothing reaches the site');

  await fs.rename(collFile('plener', '_kolekce.yaml'), collFile('plener', '_index.yaml'));
  await fs.rename(collFile('plener', '_uvod.jpg'), collFile('plener', '_cover.jpg'));
  const fixed = await run(opts());
  assert.equal(fixed.ok, true, fixed.problems.join('\n'));
  assert.equal(YAML.parse(await fs.readFile(collFile('plener', '_index.yaml'), 'utf8')).title, 'Můj plenér');
});

test('collections: a cover photo (_cover.jpg) gets web sizes; removing it or the collection cleans up', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener' });
  await addCover('plener');
  await setCollection('plener', 'title: Plenér\n');
  await run(opts());
  const info = JSON.parse(await fs.readFile(path.join(siteDir, 'public/tvorba/kolekce/plener/_cover/info.json'), 'utf8'));
  assert.equal(info.alt, 'Plenér');
  assert.deepEqual(info.widths, [40]);
  assert.equal((await run(opts())).processed, 0);

  await fs.rm(collFile('plener', '_cover.jpg'));
  await run(opts());
  assert.ok(!(await exists(path.join(siteDir, 'public/tvorba/kolekce/plener/_cover'))));
  assert.ok(await exists(path.join(siteDir, 'content/tvorba/plener/_index.yaml')));

  await fs.rm(path.join(contentDir, 'tvorba/plener'), { recursive: true });
  const r = await run(opts());
  assert.ok(r.pruned.includes('content/tvorba/plener/_index.yaml'));
  assert.ok(r.pruned.includes('content/tvorba/plener/rano.yaml'));
  assert.ok(!(await exists(path.join(siteDir, 'content/tvorba'))), 'empty folders go too');
});

test('collections: a folder with just a cover photo is a collection with a skeleton too', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addCover('jaro-na-zahrade');
  const r = await run(opts());
  assert.ok(r.created.includes('tvorba/jaro-na-zahrade/_index.yaml'));
  assert.equal(YAML.parse(await fs.readFile(collFile('jaro-na-zahrade', '_index.yaml'), 'utf8')).title, 'Jaro na zahrade');
});

test('collections: collection:, a missing title, nested collections, clashing names and kolekce/ stop the run', async () => {
  const problemsOf = async () => {
    const r = await run(opts());
    assert.equal(r.ok, false);
    return r.problems.join('\n');
  };
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ncollection: plener\n');
  assert.match(await problemsOf(), /tvorba\/rano\.yaml: "collection:" is not used any more, a work belongs to a collection by lying in its folder/);
  await setYaml('2026', 'rano', `id: ${await idOf('2026', 'rano')}\ntitle: Ráno\ndate: 2026-06-14\n`);

  await setCollection('plener', 'description: bez názvu\n');
  assert.match(await problemsOf(), /tvorba\/plener\/_index\.yaml: missing title/);
  await setCollection('plener', 'title: Plenér\n');

  await addWork('2026', 'vnoreny', 'title: V\ndate: 2026-06-14\n', { collection: 'plener/podkolekce' });
  assert.match(await problemsOf(), /tvorba\/plener\/podkolekce\/: .*collections cannot be nested/);
  await fs.rm(path.join(contentDir, 'tvorba/plener/podkolekce'), { recursive: true });

  await setCollection('Plenér', 'title: Druhý plenér\n');
  assert.match(await problemsOf(), /gives the same web address "plener"/);
  await fs.rm(path.join(contentDir, 'tvorba/Plenér'), { recursive: true });

  await fs.mkdir(path.join(contentDir, 'kolekce'));
  assert.match(await problemsOf(), /kolekce\/: collections are folders in tvorba\/ now/);
  await fs.rm(path.join(contentDir, 'kolekce'), { recursive: true });
  assert.equal((await run(opts())).ok, true);
});

test('exports: Instagram gets the original on paper and the detail photos in 4:5, never mockups', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmeta_instagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await addDetail('2026', 'rano', '1-kvet.jpg');
  await addDetail('2026', 'rano', '2-lodka.jpg');
  await run(opts());
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), ['-clean.jpg', '-detail-1-kvet.jpg', '-detail-2-lodka.jpg']);
  const { width: W, height: H } = config.images.instagram;
  for (const f of await exportsOf('instagram', '2026', 'rano')) {
    const { width, height } = await sharp(path.join(contentDir, 'export/instagram/2026', `rano-${await idOf('2026', 'rano')}${f}`)).metadata();
    assert.deepEqual([width, height], [W, H], f);
  }
});

test('exports: Fler gets the original and every mockup with the watermark, only for works on sale', async () => {
  await addWork('2026', 'volny', 'title: Volný\ndate: 2026-06-14\nmeta_instagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await addDetail('2026', 'volny', 'kvet.jpg');
  await addWork('2026', 'doma', 'title: Doma\ndate: 2026-06-14\nmeta_instagram: true\nstatus: not-for-sale\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const scenes = (await infoOf('2026', 'volny')).mockups.map((m) => `-mockup-${m.scene}.jpg`);
  assert.deepEqual(await exportsOf('fler', '2026', 'volny'), ['.jpg', ...scenes].sort());
  // the watermark changes the pixels of the bottom right corner against a plain resize of the same image
  const key = `volny-${await idOf('2026', 'volny')}`;
  const flerFile = path.join(contentDir, 'export/fler/2026', `${key}.jpg`);
  const { width, height } = await sharp(flerFile).metadata();
  const plain = await sharp(path.join(contentDir, 'tvorba/volny.jpg')).resize(width, height).raw().toBuffer();
  const signed = await sharp(flerFile).raw().toBuffer();
  assert.notDeepEqual(signed, plain);
  // a work that is not for sale has Instagram exports only
  assert.deepEqual(await exportsOf('fler', '2026', 'doma'), []);
  assert.deepEqual(await exportsOf('instagram', '2026', 'doma'), ['-clean.jpg']);
});

test('exports: removing a detail photo removes its Instagram export', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmeta_instagram: true\n');
  await addDetail('2026', 'rano', 'kvet.jpg');
  await run(opts());
  await fs.rm(path.join(contentDir, 'tvorba/rano'), { recursive: true });
  await run(opts());
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), ['-clean.jpg']);
});

test('validation: a work on sale without a price stops the run', async () => {
  await addWork('2026', 'bez-ceny', 'title: Bez ceny\ndate: 2026-06-14\nstatus: reserved\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /status "reserved" needs a price/);
});

test('detail captions: a caption for a missing detail photo stops the run, valid captions reach the public copy', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ndetails:\n  1 Květ: Květ zblízka\n  lodka: Loďka\n');
  await addDetail('2026', 'rano', '1-kvet.jpg');
  let r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /no detail photo "lodka"/);

  await addDetail('2026', 'rano', 'lodka.jpg');
  r = await run(opts());
  assert.equal(r.ok, true);
  const copy = YAML.parse(await fs.readFile(path.join(siteDir, 'content/tvorba/rano.yaml'), 'utf8'));
  assert.deepEqual(copy.details, { '1 Květ': 'Květ zblízka', lodka: 'Loďka' });
});

test('exports: renaming or deleting a work removes its old exports on both platforms', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmeta_instagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await addDetail('2026', 'rano', 'kvet.jpg');
  await addWork('2025', 'stary', 'title: Starý\ndate: 2025-03-01\nmeta_instagram: true\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const id = await idOf('2026', 'rano');
  const oldId = await idOf('2025', 'stary');
  const flerBefore = await exportsOf('fler', '2026', 'rano');
  const stareFler = await exportsOf('fler', '2025', 'stary');
  assert.equal(flerBefore.length, 4);
  assert.equal(stareFler.length, 4);

  // rename: same id, new slug (the detail folder moves with it)
  const dir = path.join(contentDir, 'tvorba');
  for (const [from, to] of [['rano.yaml', 'rano-u-rybnika.yaml'], ['rano.jpg', 'rano-u-rybnika.jpg'], ['rano', 'rano-u-rybnika']]) {
    await fs.rename(path.join(dir, from), path.join(dir, to));
  }
  // delete: the work of 2025
  for (const f of ['stary.yaml', 'stary.jpg']) await fs.rm(path.join(contentDir, 'tvorba', f));

  const r = await run(opts());
  const exportsPruned = r.pruned.filter((p) => p.startsWith('export/')).sort();
  assert.deepEqual(exportsPruned, [
    ...flerBefore.map((f) => `export/fler/2026/rano-${id}${f}`),
    `export/instagram/2026/rano-${id}-clean.jpg`,
    `export/instagram/2026/rano-${id}-detail-kvet.jpg`,
    ...stareFler.map((f) => `export/fler/2025/stary-${oldId}${f}`),
    `export/instagram/2025/stary-${oldId}-clean.jpg`,
  ].sort());
  // nothing of the old names is left, the renamed work has fresh exports
  for (const sub of ['instagram', 'fler']) {
    const all = await fs.readdir(path.join(contentDir, 'export', sub, '2026'));
    assert.ok(all.every((f) => f.startsWith(`rano-u-rybnika-${id}`)), `${sub}: ${all}`);
    assert.ok(!(await exists(path.join(contentDir, 'export', sub, '2025'))), `${sub}/2025 removed`);
  }
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano-u-rybnika'), ['-clean.jpg', '-detail-kvet.jpg']);
  assert.equal((await exportsOf('fler', '2026', 'rano-u-rybnika')).length, 4);
});

test('exports: only=<slug> never prunes exports, unknown files in export/ are left alone', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmeta_instagram: true\n');
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-15\nmeta_instagram: true\n');
  await run(opts());
  const vecerId = await idOf('2026', 'vecer');
  await fs.writeFile(path.join(contentDir, 'export/instagram/2026/poznamky.txt'), 'x');
  await fs.rm(path.join(contentDir, 'tvorba/vecer.yaml'));
  await fs.rm(path.join(contentDir, 'tvorba/vecer.jpg'));

  await run(opts({ only: ['rano'] }));
  assert.ok(await exists(path.join(contentDir, 'export/instagram/2026', `vecer-${vecerId}-clean.jpg`)));

  const r = await run(opts());
  assert.ok(r.pruned.includes(`export/instagram/2026/vecer-${vecerId}-clean.jpg`));
  assert.ok(await exists(path.join(contentDir, 'export/instagram/2026/poznamky.txt')));
});

test('exports: a stale detail export is removed even when the work is not regenerated', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmeta_instagram: true\n');
  await addDetail('2026', 'rano', 'kvet.jpg');
  await run(opts());
  const id = await idOf('2026', 'rano');
  // e.g. left behind by an interrupted run or an older pipeline version
  const stale = path.join(contentDir, 'export/instagram/2026', `rano-${id}-detail-lodka.jpg`);
  await fs.copyFile(path.join(contentDir, 'export/instagram/2026', `rano-${id}-detail-kvet.jpg`), stale);

  const r = await run(opts());
  assert.equal(r.processed, 0);
  assert.deepEqual(r.pruned, [`export/instagram/2026/rano-${id}-detail-lodka.jpg`]);
  assert.ok(!(await exists(stale)));
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), ['-clean.jpg', '-detail-kvet.jpg']);
});

test('exports: stale Fler exports are removed even when the work is not regenerated', async () => {
  await addWork('2026', 'volny', 'title: Volný\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n');
  await addWork('2026', 'doma', 'title: Doma\ndate: 2026-06-14\nstatus: not-for-sale\nsize_cm: [40, 30]\nmockups: true\n');
  await run(opts());
  const flerDir = path.join(contentDir, 'export/fler/2026');
  const volny = `volny-${await idOf('2026', 'volny')}`;
  const doma = `doma-${await idOf('2026', 'doma')}`;
  // e.g. left behind by an interrupted run: a mockup of a scene the work does not have,
  // Fler exports of a work that is not for sale, an Instagram mockup (never allowed)
  const src = path.join(flerDir, `${volny}.jpg`);
  const stale = [
    path.join(flerDir, `${volny}-mockup-zahrada.jpg`),
    path.join(flerDir, `${doma}.jpg`),
    path.join(flerDir, `${doma}-mockup-police.jpg`),
    path.join(contentDir, 'export/instagram/2026', `${volny}-wall.jpg`),
  ];
  for (const f of stale) {
    await fs.mkdir(path.dirname(f), { recursive: true }); // no work asks for Instagram, the folder does not exist
    await fs.copyFile(src, f);
  }

  const r = await run(opts());
  assert.equal(r.processed, 0);
  assert.deepEqual(r.pruned.sort(), stale.map((f) => path.relative(contentDir, f)).sort());
  for (const f of stale) assert.ok(!(await exists(f)), f);
  assert.equal((await exportsOf('fler', '2026', 'volny')).length, 4);
});

test('collections: cover names a published work of the collection and reaches the public copy', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener' });
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-20\n', { collection: 'plener' });
  await addWork('2026', 'jinde', 'title: Jinde\ndate: 2026-06-21\n');
  await addWork('2026', 'skica', 'title: Skica\ndate: 2026-06-22\nmeta_draft: true\n', { collection: 'plener' });
  await run(opts());
  const [rano, jinde, skica] = await Promise.all(['rano', 'jinde', 'skica'].map((s) => idOf('2026', s)));
  const setCover = (cover) => setCollection('plener', `title: Plenér\ncover: ${cover}\n`);

  await setCover(rano);
  assert.equal((await run(opts())).ok, true);
  assert.equal(YAML.parse(await fs.readFile(path.join(siteDir, 'content/tvorba/plener/_index.yaml'), 'utf8')).cover, rano);

  const problemFor = async (cover) => {
    await setCover(cover);
    const r = await run(opts());
    assert.equal(r.ok, false, cover);
    return r.problems.join('\n');
  };
  assert.match(await problemFor('zzzzz'), /cover zzzzz: zzzzz is not the id of any work/);
  assert.match(await problemFor(jinde), /\(Jinde\) is not in this collection/);
  assert.match(await problemFor(skica), /\(Skica\) is a draft/);

  await setCover(rano);
  await addCover('plener');
  assert.match((await run(opts())).problems.join('\n'), /cover .* and the cover photo _cover\.jpg both set/);
});

test('photos: focus goes to the public copy, an invalid focus stops the run', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addPhoto('portret');
  await addPhoto('o-mne-uvod', 'alt: Plenér\nfocus: [80, 65]\n');
  await run(opts());
  const copyOfPhoto = async (name) => YAML.parse(await fs.readFile(path.join(siteDir, 'content/fotky', `${name}.yaml`), 'utf8'));
  assert.deepEqual((await copyOfPhoto('portret')).focus, [50, 50]); // skeleton says [50, 50]
  assert.deepEqual((await copyOfPhoto('o-mne-uvod')).focus, [80, 65]);

  for (const focus of ['[120, 50]', '[50]', '"vpravo"', '[a, b]']) {
    await fs.writeFile(path.join(contentDir, 'fotky/o-mne-uvod.yaml'), `alt: Plenér\nfocus: ${focus}\n`);
    const r = await run(opts());
    assert.equal(r.ok, false, focus);
    assert.match(r.problems.join('\n'), /fotky\/o-mne-uvod\.yaml: focus must be \[x, y\]/, focus);
  }
});

test('collections: cover can be a detail photo of a work; aspect and focus reach the public copy', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener' });
  await addDetail('2026', 'rano', '1 Květy.jpg');
  await run(opts());
  const id = await idOf('2026', 'rano');
  await setCollection('plener', `title: Plenér\ncover: ${id}#1-kvety\naspect: "2:1"\nfocus: [30, 70]\n`);
  assert.equal((await run(opts())).ok, true);
  const copy = YAML.parse(await fs.readFile(path.join(siteDir, 'content/tvorba/plener/_index.yaml'), 'utf8'));
  assert.deepEqual(copy, { title: 'Plenér', description: null, cover: `${id}#1-kvety`, aspect: '2:1', focus: [30, 70] });

  await setCollection('plener', `title: Plenér\ncover: ${id}#lodka\n`);
  let r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /Ráno has no detail photo "lodka" \(folder tvorba\/plener\/rano\/\)/);

  await setCollection('plener', `title: Plenér\ncover: ${id}\naspect: "3:2"\nfocus: [50, 150]\n`);
  r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /tvorba\/plener\/_index\.yaml: focus must be \[x, y\]/);
});

test('collections: a chosen cover with aspect or focus is cropped (page and share image), otherwise whole', async () => {
  // a panorama 90 × 30 work: left third red, middle green, right third blue
  const third = (c) => sharp({ create: { width: 30, height: 30, channels: 3, background: c } }).png().toBuffer();
  const panorama = await sharp({ create: { width: 90, height: 30, channels: 3, background: '#000' } })
    .composite([{ input: await third('#ff0000'), left: 0, top: 0 }, { input: await third('#00ff00'), left: 30, top: 0 }, { input: await third('#0000ff'), left: 60, top: 0 }])
    .jpeg({ quality: 100 }).toBuffer();
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener', image: false });
  await fs.writeFile(collFile('plener', 'rano.jpg'), panorama);
  await run(opts());
  const id = await idOf('2026', 'rano');
  const og = path.join(siteDir, 'public/tvorba/kolekce/plener/og.jpg');
  const dominant = async () => {
    // read the bytes: sharp caches files by path, the same path would return the old image
    const { channels } = await sharp(await fs.readFile(og)).stats();
    return channels.slice(0, 3).map((ch) => Math.round(ch.mean));
  };

  // random cover (no cover): no share crop, the site shares the work's og.jpg
  assert.ok(!(await exists(og)));
  // cover without a crop: the whole work, again the work's own og.jpg
  await setCollection('plener', `title: Plenér\ncover: ${id}\n`);
  assert.equal((await run(opts())).ok, true);
  assert.ok(!(await exists(og)));

  await setCollection('plener', `title: Plenér\ncover: ${id}\naspect: "3:2"\nfocus: [0, 50]\n`);
  await run(opts());
  const { width, height } = await sharp(await fs.readFile(og)).metadata();
  assert.deepEqual([width, height], [config.images.og.width, config.images.og.height]);
  const [r, , b] = await dominant();
  assert.ok(r > 150 && b < 100, `left crop is mostly red: ${await dominant()}`);
  // unchanged input → the file is not rewritten
  const mtime = (await fs.stat(og)).mtimeMs;
  await run(opts());
  assert.equal((await fs.stat(og)).mtimeMs, mtime);
  await setCollection('plener', `title: Plenér\ncover: ${id}\naspect: "3:2"\nfocus: [100, 50]\n`);
  await run(opts());
  const [r2, , b2] = await dominant();
  assert.ok(b2 > 150 && r2 < 100, `right crop is mostly blue: ${await dominant()}`);
  // another aspect ratio than the share image's: the crop sits on paper (the corner is paper, the middle the crop)
  await setCollection('plener', `title: Plenér\ncover: ${id}\naspect: "1:1"\nfocus: [0, 50]\n`);
  await run(opts());
  const pixel = async (left, top) => [...(await sharp(await fs.readFile(og)).extract({ left, top, width: 1, height: 1 }).raw().toBuffer())];
  const [cr, , cb] = await pixel(config.images.og.width / 2, config.images.og.height / 2);
  assert.ok(cr > 150 && cb < 100, `middle is the red square: ${cr},${cb}`);
  assert.ok((await pixel(2, 2)).every((c) => c > 200), 'corner is paper');

  // own photo: whole on paper (both ends visible); aspect alone crops it around the centre (green)
  await fs.writeFile(collFile('plener', '_cover.jpg'), panorama);
  await setCollection('plener', 'title: Plenér\n');
  assert.equal((await run(opts())).ok, true);
  const [r3, , b3] = await dominant();
  assert.ok(r3 > 150 && b3 > 150, `whole photo on paper: ${await dominant()}`);
  await setCollection('plener', 'title: Plenér\naspect: "3:2"\n');
  assert.equal((await run(opts())).ok, true);
  const [r4, g4, b4] = await dominant();
  assert.ok(g4 > 150 && r4 < 150 && b4 < 150, `own photo cropped around the centre: ${r4},${g4},${b4}`);
  // a random cover is never cropped: aspect or focus there is an error
  await fs.rm(collFile('plener', '_cover.jpg'));
  await setCollection('plener', 'title: Plenér\nfocus: [0, 50]\n');
  const bad = await run(opts());
  assert.match(bad.problems.join('\n'), /focus crops only a chosen cover/);

  // collection gone → share image and the empty og folders are removed
  await fs.rm(path.join(contentDir, 'tvorba/plener'), { recursive: true });
  const gone = await run(opts());
  assert.ok(gone.pruned.includes('public/tvorba/kolekce/plener/og.jpg'));
  assert.ok(!(await exists(path.join(siteDir, 'public/og'))));
});

test('collections: a detail photo as cover gets a share image, cropped only with focus', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n', { collection: 'plener' });
  await addDetail('2026', 'rano', 'kvet.jpg', '#113355');
  await run(opts());
  const og = path.join(siteDir, 'public/tvorba/kolekce/plener/og.jpg');
  await setCollection('plener', `title: Plenér\ncover: ${await idOf('2026', 'rano')}#kvet\n`);
  await run(opts());
  assert.ok(await exists(og), 'whole detail on paper');
  await setCollection('plener', `title: Plenér\ncover: ${await idOf('2026', 'rano')}#kvet\naspect: "3:2"\nfocus: [50, 50]\n`);
  await run(opts());
  const { channels } = await sharp(await fs.readFile(og)).stats();
  // the detail is #113355 (dark blue), the work master #88aacc (light blue)
  assert.ok(channels[2].mean < 110, `share image comes from the detail: ${channels.map((c) => Math.round(c.mean))}`);
});

test('share image: every work gets og.jpg, the whole work on paper in 3:2, listed in info.json', async () => {
  // a tall work (addWork makes wide masters)
  const dir = path.join(contentDir, 'tvorba');
  await fs.mkdir(dir, { recursive: true });
  await sharp({ create: { width: 300, height: 600, channels: 3, background: '#223344' } }).jpeg().toFile(path.join(dir, 'vysoky.jpg'));
  await fs.writeFile(path.join(dir, 'vysoky.yaml'), 'title: Vysoký\ndate: 2026-06-14\n');
  await run(opts());
  const info = await infoOf('2026', 'vysoky');
  const { width: W, height: H, background } = config.images.og;
  assert.deepEqual(info.og, { width: W, height: H });
  const file = path.join(await workDir('2026', 'vysoky'), 'og.jpg');
  const buf = await fs.readFile(file);
  const meta = await sharp(buf).metadata();
  assert.deepEqual([meta.width, meta.height], [W, H]);
  // not cropped: the sides are paper, the middle is the work
  const px = async (left, top) => [...(await sharp(buf).extract({ left, top, width: 1, height: 1 }).raw().toBuffer())];
  const paper = [1, 3, 5].map((i) => parseInt(background.slice(i, i + 2), 16));
  for (const [l, t] of [[5, 5], [W - 6, H - 6], [5, H / 2]]) {
    (await px(l, t)).forEach((v, i) => assert.ok(Math.abs(v - paper[i]) < 8, `paper at ${l},${t}: ${v} vs ${paper[i]}`));
  }
  const mid = await px(W / 2, H / 2);
  assert.ok(mid[2] < 100, `work in the middle: ${mid}`);
});

test('test data: the real content refuses test works and collections and the marker; nothing is written', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addWork('2026', 'demo-kytice', 'title: Kytice\ndate: 2026-06-14\n');
  await setCollection('demo-plener', 'title: Plenér\n');
  await fs.writeFile(path.join(contentDir, 'demo-content.yaml'), '# test data\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  const text = r.problems.join('\n');
  for (const where of ['tvorba/demo-kytice.yaml', 'tvorba/demo-plener/_index.yaml']) {
    assert.match(text, new RegExp(`${where.replace(/[./]/g, '\\$&')}: test data do not belong in the real content`), where);
  }
  assert.match(text, /demo-content\.yaml: this content is the test data/);
  assert.ok(!text.includes('tvorba/rano.yaml'));
  assert.ok(!(await exists(path.join(siteDir, 'public/tvorba'))));
});

test('test data: the demo data set needs the marker and "demo-" names; no demo attribute anywhere', async () => {
  await addWork('2026', 'demo-rano', 'title: Ráno\ndate: 2026-06-14\n');
  let r = await run(opts({ dataset: 'demo' }));
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /demo-content\.yaml missing/);
  await fs.writeFile(path.join(contentDir, 'demo-content.yaml'), '# test data\n');
  r = await run(opts({ dataset: 'demo' }));
  assert.equal(r.ok, true, r.problems.join('\n'));
  // skeletons of the year and the home page carry no test data attribute
  for (const f of ['tvorba/demo-rano.yaml', 'roky/2026.yaml', '_index.yaml']) {
    assert.doesNotMatch(await fs.readFile(path.join(contentDir, f), 'utf8'), /^demo:/m, f);
  }
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-14\n');
  r = await run(opts({ dataset: 'demo' }));
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /vecer\.yaml: names of test works and collections start with "demo-"/);
});

test('test data: a leftover demo attribute is an unknown attribute', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\ndemo: true\n');
  const r = await run(opts());
  assert.equal(r.ok, true, r.problems.join('\n'));
  assert.match(await fs.readFile(path.join(contentDir, 'tvorba/rano.yaml'), 'utf8'), /# NEZNÁMÝ[^\n]*\ndemo: true/);
});

test('exports: Instagram only for works with instagram: true; switching it off removes the exports', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addDetail('2026', 'rano', 'kvet.jpg');
  await addWork('2026', 'vecer', 'title: Večer\ndate: 2026-06-14\nmeta_instagram: false\n');
  await addWork('2026', 'noc', 'title: Noc\ndate: 2026-06-14\nmeta_instagram: true\n');
  await run(opts());
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), []);
  assert.deepEqual(await exportsOf('instagram', '2026', 'vecer'), []);
  assert.deepEqual(await exportsOf('instagram', '2026', 'noc'), ['-clean.jpg']);

  // switching it on regenerates the work with its details, switching it off removes the exports
  const id = await idOf('2026', 'rano');
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\nmeta_instagram: true\n`);
  assert.equal((await run(opts())).processed, 1);
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), ['-clean.jpg', '-detail-kvet.jpg']);
  await setYaml('2026', 'rano', `id: ${id}\ntitle: Ráno\ndate: 2026-06-14\n`);
  await run(opts());
  assert.deepEqual(await exportsOf('instagram', '2026', 'rano'), []);
});

test('validation: meta_instagram must be true or false', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\nmeta_instagram: ano\n');
  const r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /meta_instagram must be true or false/);
});

test('prepare only (branches): skeletons, ids and checks, but no site data, images or exports', async () => {
  await addWork('2026', 'novy', undefined);
  await addWork('2026', 'hotovy', 'title: Hotový\ndate: 2026-06-14\nmeta_instagram: true\n');
  const r = await run(opts({ prepareOnly: true, today: new Date('2026-05-01') }));
  assert.equal(r.ok, true);
  assert.equal(r.prepared, true);
  assert.deepEqual(r.created, ['tvorba/novy.yaml', 'roky/2026.yaml', '_index.yaml']);
  assert.equal(r.assigned.length, 1);
  const skeleton = YAML.parse(await fs.readFile(path.join(contentDir, 'tvorba/novy.yaml'), 'utf8'));
  assert.equal(skeleton.date, '2026-05-01', 'a new work is dated today');
  assert.equal(skeleton.meta_draft, true);
  assert.equal(skeleton.title, 'Novy');
  assert.equal(skeleton.meta_instagram, false);
  assert.ok(await idOf('2026', 'hotovy'));
  for (const p of ['content', 'public']) assert.ok(!(await exists(path.join(siteDir, p))), p);
  assert.ok(!(await exists(path.join(contentDir, 'export'))));

  // problems are reported as in a full run
  await setYaml('2026', 'hotovy', `id: ${await idOf('2026', 'hotovy')}\ntitle: Hotový\ndate: 2026-06-14\nstatus: available\n`);
  const bad = await run(opts({ prepareOnly: true }));
  assert.equal(bad.ok, false);
  assert.match(bad.problems.join('\n'), /needs a price/);
});

test('mockups: a master with surroundings (sheet box in XMP) is framed without them; the web image keeps them', async () => {
  // blue sheet with a magenta margin around it (a colour that no interior scene has), as `npm run straighten` produces with --margin
  const master = async (file, withBox) => {
    let img = sharp({ create: { width: 100, height: 80, channels: 3, background: '#ff00ff' } })
      .composite([{ input: await sharp({ create: { width: 80, height: 60, channels: 3, background: '#2040a0' } }).png().toBuffer(), left: 10, top: 10 }]);
    img = sharp(await img.png().toBuffer());
    if (withBox) img = img.withXmp(sheetXmp([0.1, 0.125, 0.9, 0.875]));
    await img.jpeg({ quality: 95 }).toFile(file);
  };
  const dir = path.join(contentDir, 'tvorba');
  await fs.mkdir(dir, { recursive: true });
  await master(path.join(dir, 'oriznuty.jpg'), true);
  await master(path.join(dir, 'celek.jpg'), false);
  for (const slug of ['oriznuty', 'celek']) {
    await fs.writeFile(path.join(dir, `${slug}.yaml`), `title: ${slug}\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\n`);
  }
  assert.equal((await run(opts())).ok, true);
  // magenta pixels, also after the mockup's light and shadow: red and blue clearly above green
  const magenta = async (file) => {
    const { data } = await sharp(await fs.readFile(file)).raw().toBuffer({ resolveWithObject: true });
    let n = 0;
    for (let i = 0; i < data.length; i += 3) if (data[i] - data[i + 1] > 70 && data[i + 2] - data[i + 1] > 70) n++;
    return n;
  };
  const mockupFiles = async (slug) => {
    const d = await workDir('2026', slug);
    return (await fs.readdir(d)).filter((f) => f.startsWith('mockup-') && f.endsWith('.jpg')).map((f) => path.join(d, f));
  };
  assert.ok((await mockupFiles('oriznuty')).length > 0);
  for (const f of await mockupFiles('oriznuty')) assert.equal(await magenta(f), 0, `no margin in ${path.basename(f)}`);
  let control = 0;
  for (const f of await mockupFiles('celek')) control += await magenta(f);
  assert.ok(control > 0, 'without the box the margin is framed as part of the work');
  // the web image of the work keeps the surroundings
  assert.ok((await magenta(path.join(await workDir('2026', 'oriznuty'), '40.jpg'))) > 0);
});

test('skeletons contain every supported attribute (work, collection, photo) and pass the checks', async () => {
  await addWork('2026', 'novy', undefined, { collection: 'nova-kolekce' });
  await addPhoto('kontakt');
  const r = await run(opts({ today: new Date('2026-05-01') }));
  assert.equal(r.ok, true, r.problems.join('\n'));
  const keysOf = async (...p) => {
    const text = await fs.readFile(path.join(contentDir, ...p), 'utf8');
    // commented-out optional attributes ("# aspect: …") count as there
    return [...Object.keys(YAML.parse(text)), ...[...text.matchAll(/^# (\w+): /gm)].map((m) => m[1])];
  };
  const missing = (fields, keys) => fields.filter((f) => !keys.includes(f));
  // skeletons are built from scripts/lib/schema.mjs, see WORK_FIELDS etc.
  assert.deepEqual(missing(WORK_FIELDS, await keysOf('tvorba/nova-kolekce/novy.yaml')), [], 'WORK_SCHEMA');
  assert.deepEqual(missing(COLLECTION_FIELDS, await keysOf('tvorba/nova-kolekce/_index.yaml')), [], 'COLLECTION_SCHEMA');
  assert.deepEqual(missing(PHOTO_FIELDS, await keysOf('fotky/kontakt.yaml')), [], 'PHOTO_SCHEMA');
  assert.deepEqual(r.updated, [], 'new skeletons are already in line');
});

test('existing files get every supported attribute on every run, on a branch too; nothing else changes', async () => {
  await addWork('2026', 'rano', 'id: k3f9a\ntitle: Ráno\ndate: 2026-06-14\nsize_cm: [40, 30]   # změřeno\nmockup: true\n');
  await setCollection('plener', 'title: Plenér\n');
  await addWork('2026', 'vecer', 'id: m7q2x\ntitle: Večer\ndate: 2026-06-15\n', { collection: 'plener' });
  await addPhoto('kontakt', 'alt: Pavla\n');

  const r = await run(opts({ prepareOnly: true }));
  assert.equal(r.ok, true, r.problems.join('\n'));
  assert.deepEqual(r.updated.map((u) => u.split(':')[0]).sort(), ['fotky/kontakt.yaml', 'tvorba/plener/_index.yaml', 'tvorba/plener/vecer.yaml', 'tvorba/rano.yaml']);
  assert.match(r.updated.find((u) => u.startsWith('tvorba/rano.yaml')), /doplněno description, status, technique \(DOPLNIT\); doplněno meta_draft, meta_instagram, featured, mockups, tags \(výchozí hodnota\); neznámé mockup \(NEZNÁMÝ\)/);

  const text = await fs.readFile(path.join(contentDir, 'tvorba/rano.yaml'), 'utf8');
  const data = YAML.parse(text);
  const commented = WORK_SCHEMA.fields.filter((f) => f.commented).map((f) => f.key);
  assert.deepEqual(Object.keys(data), [...WORK_FIELDS.filter((k) => !commented.includes(k)), 'mockup']);
  assert.match(text, /\n# NEPOVINNÉ\. Cena v Kč.*\n# price: 2500\n/, 'price and fler are commented out');
  assert.equal(data.meta_draft, false, 'a work without draft stays published');
  assert.equal(data.description, null, 'no placeholder text reaches the site');
  assert.match(text, /# změřeno\n# Šířka × výška v cm[^\n]*\n[^\n]*\nsize_cm: \[40, 30\]/);
  assert.match(text, /^# Rohy listu[^\n]*\n(# [^\n]*\n){3}meta_corners:\n  photo: \[64, 48\]\n(  (tl|tr|br|bl): \[\d+, \d+\]\n){4}\n# true = rozpracovaný[^\n]*\nmeta_draft: false\n/,
    'settled: no DOPLNIT; meta_ attributes come first, the corners of the sheet detected');
  assert.match(text, /# NEZNÁMÝ atribut[^\n]*\nmockup: true\n$/);
  assert.deepEqual(Object.keys(YAML.parse(await fs.readFile(path.join(contentDir, 'fotky/kontakt.yaml'), 'utf8'))), PHOTO_FIELDS.filter((k) => k !== 'caption'));

  // published works with DOPLNIT left are listed (drafts are not): rano and vecer have no draft, so they are published
  assert.deepEqual(r.pending.map((p) => p.split(':')[0]).sort(), ['tvorba/plener/vecer.yaml', 'tvorba/rano.yaml']);
  assert.match(r.pending.find((p) => p.startsWith('tvorba/rano.yaml')), /: description, status, technique$/, "only attributes still to check: not settled, not commented out");

  // the second run has nothing to do, the site data are the same as from the old files
  const second = await run(opts());
  assert.deepEqual(second.updated, []);
  assert.equal(second.pending.length, 2, 'still listed until DOPLNIT is removed');
  const vecer = path.join(contentDir, 'tvorba/plener/vecer.yaml');
  await fs.writeFile(vecer, (await fs.readFile(vecer, 'utf8')).replaceAll('# DOPLNIT ', '# '));
  assert.deepEqual((await run(opts())).pending.map((p) => p.split(':')[0]), ['tvorba/rano.yaml']);
  // a draft is not listed
  const rano = path.join(contentDir, 'tvorba/rano.yaml');
  await fs.writeFile(rano, (await fs.readFile(rano, 'utf8')).replace('meta_draft: false', 'meta_draft: true'));
  assert.deepEqual((await run(opts())).pending, []);
  await fs.writeFile(rano, (await fs.readFile(rano, 'utf8')).replace('meta_draft: true', 'meta_draft: false'));
  await run(opts());
  const copy = YAML.parse(await fs.readFile(path.join(siteDir, 'content/tvorba/rano.yaml'), 'utf8'));
  assert.equal(copy.title, 'Ráno');
  assert.equal(copy.mockup, undefined);
});

test('attributes: a former name (draft, instagram) stops the run and the file is left alone, nothing is written', async () => {
  const old = 'id: k3f9a\ntitle: Ráno\ndate: 2026-06-14\ndraft: true\ninstagram: true\n';
  await addWork('2026', 'rano', old);
  for (const prepareOnly of [true, false]) {
    const r = await run(opts({ prepareOnly }));
    assert.equal(r.ok, false);
    assert.deepEqual(r.problems, ['tvorba/rano.yaml: draft: renamed to meta_draft, rename it; instagram: renamed to meta_instagram, rename it']);
    assert.equal(await fs.readFile(path.join(contentDir, 'tvorba/rano.yaml'), 'utf8'), old, 'never migrated silently');
    assert.equal(await exists(path.join(siteDir, 'content')), false, 'a draft under its old name never reaches the site');
  }
  // renamed by hand: fine, still a draft
  await fs.writeFile(path.join(contentDir, 'tvorba/rano.yaml'), old.replace('draft:', 'meta_draft:').replace('instagram:', 'meta_instagram:'));
  const r = await run(opts());
  assert.equal(r.ok, true, r.problems.join('\n'));
  assert.equal(await exists(path.join(siteDir, 'content/tvorba/rano.yaml')), false);
});

test('attributes: own private_ attributes and meta_ ones never reach the public copy; derived_ ones are refused', async () => {
  await addWork('2026', 'rano', 'id: k3f9a\ntitle: Ráno\ndate: 2026-06-14\nmeta_instagram: true\nprivate_kupec: teta\nprivate_cena_nakupu: 300\n');
  let r = await run(opts());
  assert.equal(r.ok, true, r.problems.join('\n'));
  const copy = await fs.readFile(path.join(siteDir, 'content/tvorba/rano.yaml'), 'utf8');
  assert.doesNotMatch(copy, /private_|meta_|teta/);
  const text = await fs.readFile(path.join(contentDir, 'tvorba/rano.yaml'), 'utf8');
  assert.doesNotMatch(text, /NEZNÁMÝ/);
  assert.deepEqual(Object.keys(YAML.parse(text)).slice(-2), ['private_cena_nakupu', 'private_kupec'], 'alphabetically at the end');

  await setCollection('plener', 'title: Plenér\nderived_slug: x\n');
  r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /tvorba\/plener\/_index\.yaml: derived_slug: derived_ attributes are made by the pipeline/);
});

test('derived_modified: the day the public attributes or the images of a work last changed, kept otherwise', async () => {
  await addWork('2026', 'rano', 'id: k3f9a\ntitle: Ráno\ndate: 2026-06-14\ndescription: Mlha.\n');
  const copyPath = path.join(siteDir, 'content/tvorba/rano.yaml');
  const modifiedOf = async () => YAML.parse(await fs.readFile(copyPath, 'utf8')).derived_modified;
  await run(opts({ today: new Date('2026-10-01T12:00:00Z') }));
  assert.equal(await modifiedOf(), '2026-10-01', 'a new work: the day it reached the site');

  // nothing changed: the day stays (and the file is not rewritten)
  await run(opts({ today: new Date('2026-10-05T12:00:00Z') }));
  assert.equal(await modifiedOf(), '2026-10-01');
  // a private or meta_ attribute is not a change of the page
  const yaml = path.join(contentDir, 'tvorba/rano.yaml');
  await fs.writeFile(yaml, (await fs.readFile(yaml, 'utf8')).replace('# private_note:', 'private_note:'));
  await run(opts({ today: new Date('2026-10-06T12:00:00Z') }));
  assert.equal(await modifiedOf(), '2026-10-01');

  // a public attribute changed
  await fs.writeFile(yaml, (await fs.readFile(yaml, 'utf8')).replace('Mlha.', 'Ranní mlha.'));
  await run(opts({ today: new Date('2026-10-07T12:00:00Z') }));
  assert.equal(await modifiedOf(), '2026-10-07');

  // a new master photo (images regenerated)
  await sharp({ create: { width: 64, height: 48, channels: 3, background: '#aa3322' } }).jpeg().toFile(path.join(contentDir, 'tvorba/rano.jpg'));
  await run(opts({ today: new Date('2026-10-09T12:00:00Z') }));
  assert.equal(await modifiedOf(), '2026-10-09');
  // derived_ never reaches the content repository
  assert.doesNotMatch(await fs.readFile(yaml, 'utf8'), /derived_/);
});

test('years: a skeleton per year, the public text reaches the site, the private note never; removed with the year', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  let r = await run(opts());
  assert.ok(r.created.includes('roky/2026.yaml'));
  const copyPath = path.join(siteDir, 'content/roky/2026.yaml');
  assert.equal(YAML.parse(await fs.readFile(copyPath, 'utf8')).description, '');

  await fs.writeFile(path.join(contentDir, 'roky/2026.yaml'), 'description: |\n  Rok plenérů.\nprivate_note: tajné\n');
  r = await run(opts());
  const copy = await fs.readFile(copyPath, 'utf8');
  assert.deepEqual(YAML.parse(copy), { description: 'Rok plenérů.\n' });
  assert.doesNotMatch(copy, /tajné/);

  await fs.rm(path.join(contentDir, 'roky/2026.yaml'));
  await fs.rm(path.join(contentDir, 'tvorba/rano.yaml'));
  await fs.rm(path.join(contentDir, 'tvorba/rano.jpg'));
  r = await run(opts());
  assert.ok(r.pruned.includes('content/roky/2026.yaml'));
  assert.ok(!(await exists(path.join(siteDir, 'content/roky'))));
});

test('covers of years and the home page: own photo, cover, focus; share image only for a chosen cover', async () => {
  await addWork('2026', 'rano', 'title: Ráno\ndate: 2026-06-14\n');
  await addWork('2025', 'vecer', 'title: Večer\ndate: 2025-06-14\n');
  let r = await run(opts());
  assert.equal(r.ok, true, r.problems.join('\n'));
  assert.ok(r.created.includes('_index.yaml'));
  const home = YAML.parse(await fs.readFile(path.join(siteDir, 'content/_index.yaml'), 'utf8'));
  assert.match(home.description, /^Maluji pro radost, hlavně akvarelem/);
  // random covers: no share crops, no photos
  assert.ok(!(await exists(path.join(siteDir, 'public/og.jpg'))));
  assert.ok(!(await exists(path.join(siteDir, 'public/og/years'))));

  const idRano = await idOf('2026', 'rano');
  await fs.writeFile(path.join(contentDir, '_index.yaml'), `description: Ahoj.\ncover: ${idRano}\naspect: "1:1"\nfocus: [30, 40]\n`);
  await sharp({ create: { width: 90, height: 30, channels: 3, background: '#335577' } }).jpeg().toFile(path.join(contentDir, 'roky/2025.jpg'));
  r = await run(opts());
  assert.equal(r.ok, true, r.problems.join('\n'));
  assert.ok(await exists(path.join(siteDir, 'public/og.jpg')));
  assert.ok(await exists(path.join(siteDir, 'public/tvorba/2025/og.jpg')));
  assert.ok(await exists(path.join(siteDir, 'public/tvorba/2025/_cover/info.json')));
  assert.deepEqual(YAML.parse(await fs.readFile(path.join(siteDir, 'content/_index.yaml'), 'utf8')), { description: 'Ahoj.', cover: idRano, aspect: '1:1', focus: [30, 40] });

  // a cover of another year, a year photo and a cover both set stop the run
  await fs.writeFile(path.join(contentDir, 'roky/2025.yaml'), `cover: ${idRano}\n`);
  r = await run(opts());
  assert.equal(r.ok, false);
  assert.match(r.problems.join('\n'), /roky\/2025\.yaml: cover .* and the cover photo 2025\.jpg both set/);
  await fs.rm(path.join(contentDir, 'roky/2025.jpg'));
  r = await run(opts());
  assert.match(r.problems.join('\n'), /roky\/2025\.yaml: cover .*\(Ráno\) is not in 2025/);

  // back to random: share crops and photos are removed
  await fs.writeFile(path.join(contentDir, 'roky/2025.yaml'), 'description: ""\n');
  await fs.writeFile(path.join(contentDir, '_index.yaml'), 'description: Ahoj.\n');
  r = await run(opts());
  assert.equal(r.ok, true, r.problems.join('\n'));
  assert.ok(r.pruned.includes('public/og.jpg'));
  assert.ok(r.pruned.includes('public/tvorba/2025/_cover/'));
  assert.ok(!(await exists(path.join(siteDir, 'public/og/years'))));
});

/** A master photographed on a floor: magenta floor (a colour no interior scene has), a light sheet askew with paint on it. */
async function floorMaster(slug, yaml) {
  const dir = path.join(contentDir, 'tvorba');
  await fs.mkdir(dir, { recursive: true });
  const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300"><rect width="100%" height="100%" fill="#ff00ff"/>'
    + '<polygon points="24,16 376,24 372,284 18,278" fill="#f0eee6"/><ellipse cx="200" cy="150" rx="90" ry="60" fill="#4a6fa0"/></svg>';
  await sharp(Buffer.from(svg)).jpeg({ quality: 95 }).toFile(path.join(dir, `${slug}.jpg`));
  if (yaml !== undefined) await fs.writeFile(path.join(dir, `${slug}.yaml`), yaml);
}
const magentaShare = async (buf) => {
  const { data, info } = await sharp(buf).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  let n = 0;
  for (let i = 0; i < data.length; i += 3) if (data[i] - data[i + 1] > 70 && data[i + 2] - data[i + 1] > 70) n++;
  return n / (info.width * info.height);
};
const pixel = async (file, x, y) => {
  const { data, info } = await sharp(await fs.readFile(file)).raw().toBuffer({ resolveWithObject: true });
  return [...data.subarray((y * info.width + x) * info.channels, (y * info.width + x + 1) * info.channels)];
};

test('corners: prepare only finds the corners of every work and writes the cut previews of drafts only, nothing for the site', async () => {
  await floorMaster('rozpracovany', 'meta_draft: true\ntitle: Rozpracovaný\ndate: 2026-06-14\n');
  await floorMaster('hotovy', 'meta_draft: false\ntitle: Hotový\ndate: 2026-06-14\n');
  await addWork('2026', 'bez-podlahy', 'meta_draft: true\ntitle: Bez podlahy\ndate: 2026-06-14\n');
  const previewDir = path.join(tmp, 'previews');
  const r = await run(opts({ prepareOnly: true, previewDir }));
  assert.equal(r.ok, true, r.problems.join('\n'));
  assert.deepEqual(r.detected.map((d) => d.split(':')[0]).sort(), ['tvorba/bez-podlahy.yaml', 'tvorba/hotovy.yaml', 'tvorba/rozpracovany.yaml']);
  const corners = YAML.parse(await fs.readFile(path.join(contentDir, 'tvorba/hotovy.yaml'), 'utf8')).meta_corners;
  assert.deepEqual(corners.photo, [400, 300]);
  assert.ok(corners.tl[0] >= 20 && corners.tl[0] <= 30 && corners.tl[1] >= 12 && corners.tl[1] <= 22, JSON.stringify(corners));
  // a draft whose photo has no floor needs no preview, a published work never gets one
  const id = await idOf('2026', 'rozpracovany');
  // all three, like npm run preview
  const three = ['backgrounds', 'cut', 'frames'].map((k) => `rozpracovany-${id}-${k}.jpg`);
  assert.deepEqual(r.previews, three);
  assert.deepEqual((await fs.readdir(previewDir)).sort(), three);
  assert.equal((await sharp(path.join(previewDir, `rozpracovany-${id}-frames.jpg`)).metadata()).width, 400, 'the whole photo');
  const meta = await sharp(path.join(previewDir, `rozpracovany-${id}-backgrounds.jpg`)).metadata();
  assert.equal(meta.format, 'jpeg');
  assert.ok(meta.width > meta.height * 2, 'light and dark side by side');
  for (const p of ['content', 'public']) assert.ok(!(await exists(path.join(siteDir, p))), p);
  // published, the draft's preview is gone with the next full run
  const rozpracovany = path.join(contentDir, 'tvorba/rozpracovany.yaml');
  await fs.writeFile(rozpracovany, (await fs.readFile(rozpracovany, 'utf8')).replace('meta_draft: true', 'meta_draft: false'));
  const full = await run(opts({ previewDir }));
  assert.deepEqual(full.detected, [], 'found once, kept since');
  assert.deepEqual(full.previews, []);
  assert.ok(!(await exists(previewDir)));
});

test('corners: the floor is transparent on the web, paper in the JPEG, white for Fler, gone from mockups and exports', async () => {
  await floorMaster('podlaha', 'title: Podlaha\ndate: 2026-06-14\nstatus: available\nprice: 1000\nsize_cm: [40, 30]\nmockups: true\nmeta_instagram: true\n');
  const r = await run(opts());
  assert.equal(r.ok, true, r.problems.join('\n'));
  const dir = await workDir('2026', 'podlaha');
  const info = JSON.parse(await fs.readFile(path.join(dir, 'info.json'), 'utf8'));
  assert.equal(info.transparent, true);
  assert.equal(info.dominant.startsWith('rgb('), true);
  const w = info.widths[info.widths.length - 1];
  // trimmed to the sheet (x 18–376, y 16–284 of the 400 × 300 photo): only the wedges of the sheet askew stay around it
  assert.ok(info.width >= 350 && info.width <= 362 && info.height >= 260 && info.height <= 272, `${info.width}×${info.height}`);
  // AVIF and WebP: transparent wedges, opaque middle
  for (const ext of ['webp', 'avif']) {
    const file = path.join(dir, `${w}.${ext}`);
    assert.equal((await sharp(file).metadata()).hasAlpha, true, ext);
    const { data, info: size } = await sharp(file).raw().toBuffer({ resolveWithObject: true });
    let clear = 0;
    for (let i = 3; i < data.length; i += 4) if (data[i] === 0) clear++;
    assert.ok(clear > 0, `${ext}: the floor is transparent`);
    assert.equal((await pixel(file, Math.round(size.width / 2), Math.round(size.height / 2)))[3], 255, `${ext}: the work is not`);
  }
  // JPEG: the paper of the first palette instead of the floor (the top right wedge: the sheet's corner lies lower)
  const corner = await pixel(path.join(dir, `${w}.jpg`), w - 2, 1);
  assert.ok(corner.every((c, i) => Math.abs(c - [0xf7, 0xf4, 0xee][i]) < 8), `jpeg corner ${corner}`);
  // exports: no floor anywhere; Fler on white
  const key = path.basename(dir);
  const fler = path.join(contentDir, 'export/fler/2026', `${key}.jpg`);
  assert.ok((await pixel(fler, 1, 1)).every((c) => c > 245), 'Fler: white instead of the floor');
  for (const f of [fler, path.join(contentDir, 'export/instagram/2026', `${key}-clean.jpg`), path.join(dir, 'og.jpg')]) {
    assert.ok((await magentaShare(await fs.readFile(f))) < 0.002, `no floor in ${path.basename(f)}`);
  }
  const mockups = (await fs.readdir(dir)).filter((f) => f.startsWith('mockup-') && f.endsWith('.jpg'));
  assert.ok(mockups.length > 0);
  for (const f of mockups) assert.ok((await magentaShare(await fs.readFile(path.join(dir, f)))) < 0.0005, `no floor in ${f}`);
});

test('corners: false keeps the whole photo; changing the corners regenerates; corners of another photo stop the run', async () => {
  await floorMaster('podlaha', 'meta_corners: false\ntitle: Podlaha\ndate: 2026-06-14\n');
  assert.equal((await run(opts())).ok, true);
  const dir = await workDir('2026', 'podlaha');
  const info = JSON.parse(await fs.readFile(path.join(dir, 'info.json'), 'utf8'));
  assert.equal(info.transparent, undefined);
  assert.equal(YAML.parse(await fs.readFile(path.join(contentDir, 'tvorba/podlaha.yaml'), 'utf8')).meta_corners, false, 'kept');
  assert.ok((await magentaShare(await fs.readFile(path.join(dir, '40.jpg')))) > 0.05, 'the floor stays');

  const file = path.join(contentDir, 'tvorba/podlaha.yaml');
  const set = async (value) => fs.writeFile(file, (await fs.readFile(file, 'utf8')).replace(/meta_corners:[\s\S]*?\n(?=\n|[a-z])/, `meta_corners: ${value}\n`));
  await set('{ photo: [400, 300], tl: [30, 30], tr: [30, 30], br: [30, 30], bl: [30, 30] }');
  const changed = await run(opts());
  assert.equal(changed.processed, 1, 'regenerated');
  assert.equal(JSON.parse(await fs.readFile(path.join(dir, 'info.json'), 'utf8')).transparent, true);

  await set('{ photo: [800, 600], tl: [30, 30], tr: [30, 30], br: [30, 30], bl: [30, 30] }');
  const bad = await run(opts());
  assert.equal(bad.ok, false);
  assert.match(bad.problems.join('\n'), /tvorba\/podlaha\.yaml: meta_corners belong to a photo of 800 × 600, but the photo is 400 × 300/);
});

test('corners: settings of detection and previews (search, suspicious) never regenerate a work, feather does', async () => {
  await floorMaster('podlaha', 'title: Podlaha\ndate: 2026-06-14\n');
  assert.equal((await run(opts())).processed, 1);
  const edges = config.images.edges;
  const withEdges = (over) => ({ ...config, images: { ...config.images, edges: { ...edges, ...over } } });
  assert.equal((await run(opts({ config: withEdges({ suspicious: 0.2, search: 0.2 }) }))).processed, 0);
  assert.equal((await run(opts({ config: withEdges({ feather: 0.03 }) }))).processed, 1);
});
