#!/usr/bin/env node
// Image pipeline. Reads works from the content repository (pavla-content) and produces:
//   content/works/<year>/<slug>-<id>.yaml              copy of the metadata for the site build (commit)
//   public/works/<year>/<slug>-<id>/<width>.{avif,webp,jpg}, info.json   web images (commit)
//   public/works/<year>/<slug>-<id>/mockup-<scene>-<width>.*              the work in an interior (commit)
//   public/photos/<name>/<width>.{avif,webp,jpg}, info.json                other photos of the site (commit)
//   <contentDir>/export/instagram/<year>/<key>-clean.jpg   Instagram, plain 4:5
//   <contentDir>/export/instagram/<year>/<key>-wall.jpg    Instagram, the first mockup cropped to 4:5
//   <contentDir>/export/fler/<year>/<key>.jpg              Fler, with the author's name as watermark
//
// Usage:  npm run images             (only works whose outputs are missing or older than the master)
//         npm run images -- --force  (regenerate everything)
//         npm run images -- <slug>   (a single work; skips pruning)
// Content location: images.contentDir in site.config.yaml, overridable by CONTENT_DIR.

import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import sharp from 'sharp';
import YAML from 'yaml';
import { prepareContent } from './lib/content.mjs';
import { loadScenes, pickScenes, renderMockup } from './lib/mockups.mjs';
import { preparePhotos } from './lib/photos.mjs';
import { formatSummary } from './lib/summary.mjs';
import { planPrune, validateWorks, workKey } from './lib/works.mjs';

/** Bump when the output format changes, so every work is regenerated once. */
const PIPELINE_VERSION = 3;

const siteRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const exists = (p) => fs.access(p).then(() => true, () => false);
const readJson = (p) => fs.readFile(p, 'utf8').then(JSON.parse, () => null);
const sha1 = (...parts) => {
  const h = createHash('sha1');
  for (const p of parts) h.update(typeof p === 'string' ? p : Buffer.from(p));
  return h.digest('hex').slice(0, 16);
};
const esc = (s) => String(s).replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);

const SYNC_HEADER = '# Generated by `npm run images` from pavla-content. Do not edit here, changes will be overwritten.\n';

// Load the master once: convert to sRGB and apply EXIF rotation. Metadata (EXIF, GPS) is not copied to outputs.
async function loadMaster(input) {
  const buf = await sharp(input).rotate().toColorspace('srgb').toBuffer();
  const meta = await sharp(buf).metadata();
  return { buf, width: meta.width, height: meta.height };
}

/** Writes <prefix><width>.{avif,webp,jpg} for every width that does not upscale; returns the widths. */
async function responsive(buf, srcWidth, dir, prefix, widths, quality) {
  // Never upscale: a smaller source additionally gets a variant at its full width.
  const fit = widths.filter((w) => w <= srcWidth);
  const unique = fit.length === widths.length ? fit : [...fit, srcWidth];
  for (const w of unique) {
    const base = sharp(buf).resize({ width: w, withoutEnlargement: true });
    await base.clone().avif({ quality: quality - 22, effort: 5 }).toFile(path.join(dir, `${prefix}${w}.avif`));
    await base.clone().webp({ quality }).toFile(path.join(dir, `${prefix}${w}.webp`));
    await base.clone().jpeg({ quality, mozjpeg: true, progressive: true }).toFile(path.join(dir, `${prefix}${w}.jpg`));
  }
  return unique;
}

const dominantColor = async (buf) => {
  const { dominant: d } = await sharp(buf).stats();
  return `rgb(${d.r},${d.g},${d.b})`;
};

async function web(dir, m, img, { work, picked, fingerprint }) {
  // The folder only holds generated files, so start clean (drops mockups of scenes no longer picked).
  await fs.rm(dir, { recursive: true, force: true });
  await fs.mkdir(dir, { recursive: true });
  const widths = await responsive(m.buf, m.width, dir, '', img.web.widths, img.web.quality);
  const mockups = [];
  for (const scene of picked) {
    const buf = await renderMockup(m.buf, work.size_cm, scene);
    const { width, height } = await sharp(buf).metadata();
    const mw = await responsive(buf, width, dir, `mockup-${scene.name}-`, img.mockups.widths, img.web.quality);
    mockups.push({ scene: scene.name, label: scene.label, width, height, widths: mw, dominant: await dominantColor(buf) });
  }
  // Dimensions and placeholder colour, read by the site.
  const info = { width: m.width, height: m.height, widths, dominant: await dominantColor(m.buf), mockups, fingerprint };
  await fs.writeFile(path.join(dir, 'info.json'), JSON.stringify(info, null, 2));
}

async function instagramClean(file, m, img) {
  const { width: W, height: H, background, padding } = img.instagram;
  const pad = Math.round(W * padding);
  const inner = await sharp(m.buf).resize({ width: W - 2 * pad, height: H - 2 * pad, fit: 'inside' }).toBuffer();
  await sharp({ create: { width: W, height: H, channels: 3, background } })
    .composite([{ input: inner, gravity: 'center' }])
    .jpeg({ quality: 92, mozjpeg: true })
    .toFile(file);
}

// The first mockup of the work (real scale, same scene as on the web), cropped to Instagram's 4:5.
async function instagramWall(file, m, work, scene, img) {
  const { width: W, height: H } = img.instagram;
  const buf = await renderMockup(m.buf, work.size_cm, scene, { aspect: W / H });
  await sharp(buf).resize(W, H, { fit: 'cover' }).jpeg({ quality: 92, mozjpeg: true }).toFile(file);
}

async function fler(file, m, img) {
  const f = img.fler;
  const resized = await sharp(m.buf).resize({ width: f.longEdge, height: f.longEdge, fit: 'inside', withoutEnlargement: true }).toBuffer();
  const { width, height } = await sharp(resized).metadata();
  const size = Math.round(Math.min(width, height) * 0.035);
  const margin = Math.round(size * 1.2);
  // Signature colour depends on the brightness of the corner: dark on light paper, light on dark paint.
  const cw = Math.round(width * 0.4), ch = Math.round(size * 2.5);
  const corner = await sharp(resized).extract({ left: width - cw, top: height - ch, width: cw, height: ch }).stats();
  const [r, g, b] = corner.channels.map((c) => c.mean);
  const light = 0.2126 * r + 0.7152 * g + 0.0722 * b > 150;
  const [ink, halo] = light ? ['#3a3430', '#ffffff'] : ['#ffffff', '#000000'];
  // Discreet signature in the bottom right corner, with a faint halo so it reads on light and dark areas.
  const mark = Buffer.from(`<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
    <style>text{font-family:'DejaVu Serif','Georgia',serif;font-style:italic;font-size:${size}px}</style>
    <text x="${width - margin + 1}" y="${height - margin + 1}" text-anchor="end" fill="${halo}" fill-opacity="${f.watermarkOpacity * 0.5}">${esc(f.watermark)}</text>
    <text x="${width - margin}" y="${height - margin}" text-anchor="end" fill="${ink}" fill-opacity="${f.watermarkOpacity}">${esc(f.watermark)}</text>
  </svg>`);
  await sharp(resized)
    .composite([{ input: mark }])
    .jpeg({ quality: f.quality, mozjpeg: true })
    .toFile(file);
}

/** Lists "<year>/<name>" entries one level below `root` (name without `ext` when given). */
async function listGenerated(root, ext) {
  const out = [];
  if (!(await exists(root))) return out;
  for (const year of await fs.readdir(root, { withFileTypes: true })) {
    if (!year.isDirectory()) continue;
    for (const e of await fs.readdir(path.join(root, year.name), { withFileTypes: true })) {
      if (ext ? e.isFile() && e.name.endsWith(ext) : e.isDirectory()) {
        out.push(`${year.name}/${ext ? e.name.slice(0, -ext.length) : e.name}`);
      }
    }
  }
  return out;
}

async function removeEmptyYearDirs(root) {
  if (!(await exists(root))) return;
  for (const year of await fs.readdir(root, { withFileTypes: true })) {
    const dir = path.join(root, year.name);
    if (year.isDirectory() && (await fs.readdir(dir)).length === 0) await fs.rmdir(dir);
  }
}

/**
 * Runs the whole pipeline. Returns a summary; throws on configuration errors.
 * Options: contentDir, siteDir, config, force, only (slugs), log, today, random.
 */
export async function run({
  contentDir,
  siteDir = siteRoot,
  config,
  force = false,
  only = [],
  scenesDir,
  log = console.log,
  today,
  random,
} = {}) {
  config ??= YAML.parse(await fs.readFile(path.join(siteDir, 'site.config.yaml'), 'utf8'));
  const img = config.images;
  contentDir = path.resolve(siteDir, contentDir ?? process.env.CONTENT_DIR ?? img.contentDir);
  if (!(await exists(path.join(contentDir, 'tvorba')))) {
    throw new Error(`Content not found: ${path.join(contentDir, 'tvorba')} (set images.contentDir or CONTENT_DIR)`);
  }

  const { works, created, assigned, problems: scanProblems } = await prepareContent(contentDir, { today, random });
  const photos = await preparePhotos(contentDir);
  created.push(...photos.created);
  created.forEach((p) => log(`+ new metadata skeleton: ${p}`));
  assigned.forEach((p) => log(`+ id assigned: ${p}`));
  const problems = [...scanProblems, ...validateWorks(works), ...photos.problems];
  if (problems.length) {
    return { ok: false, problems, created, assigned, processed: 0, skipped: 0, missing: [], pruned: [] };
  }
  const { scenes, text: scenesText } = await loadScenes(scenesDir);

  const metaRoot = path.join(siteDir, 'content/works');
  const webRoot = path.join(siteDir, 'public/works');
  const exportRoot = path.join(contentDir, 'export');

  let processed = 0, skipped = 0;
  const missing = [];
  for (const w of works) {
    if (only.length && !only.includes(w.slug)) continue;
    const key = workKey(w.slug, w.id);
    const rel = `${w.year}/${key}`;

    // Metadata copy for the site build; written only when it changed to keep git diffs clean.
    const metaFile = path.join(metaRoot, `${rel}.yaml`);
    const metaText = SYNC_HEADER + w.text;
    if ((await fs.readFile(metaFile, 'utf8').catch(() => null)) !== metaText) {
      await fs.mkdir(path.dirname(metaFile), { recursive: true });
      await fs.writeFile(metaFile, metaText);
    }

    const webDir = path.join(webRoot, rel);
    if (!w.masterPath) {
      // No master is fine as long as web images exist (another computer, CI).
      if (!(await exists(path.join(webDir, 'info.json')))) missing.push(rel);
      continue;
    }
    // Outputs depend on the master, the size (mockup scale) and the scenes; not on price or description.
    const master = await fs.readFile(w.masterPath);
    const fingerprint = sha1(String(PIPELINE_VERSION), master, JSON.stringify(w.data.size_cm ?? null), scenesText);
    const upToDate = (await readJson(path.join(webDir, 'info.json')))?.fingerprint === fingerprint;
    if (upToDate && !force) { skipped++; continue; }

    log(`→ ${rel}`);
    const m = await loadMaster(master);
    const picked = pickScenes(w.data.size_cm, w.id, scenes);
    if (!picked.length) log(`  ! no mockup scene is big enough for ${rel} (see mockups/scenes.yaml maxCm)`);
    await web(webDir, m, img, { work: w.data, picked, fingerprint });
    for (const sub of ['instagram', 'fler']) await fs.mkdir(path.join(exportRoot, sub, w.year), { recursive: true });
    await instagramClean(path.join(exportRoot, 'instagram', w.year, `${key}-clean.jpg`), m, img);
    if (picked.length) await instagramWall(path.join(exportRoot, 'instagram', w.year, `${key}-wall.jpg`), m, w.data, picked[0], img);
    await fler(path.join(exportRoot, 'fler', w.year, `${key}.jpg`), m, img);
    processed++;
  }

  // Remove outputs of works that were deleted or renamed in the content repository.
  const pruned = [];
  if (!only.length) {
    const wanted = works.map((w) => `${w.year}/${workKey(w.slug, w.id)}`);
    if (!wanted.length) throw new Error('No works found in the content repository, refusing to delete generated files');
    for (const rel of planPrune(await listGenerated(metaRoot, '.yaml'), wanted)) {
      await fs.rm(path.join(metaRoot, `${rel}.yaml`));
      pruned.push(`content/works/${rel}.yaml`);
    }
    for (const rel of planPrune(await listGenerated(webRoot), wanted)) {
      await fs.rm(path.join(webRoot, rel), { recursive: true });
      pruned.push(`public/works/${rel}/`);
    }
    await removeEmptyYearDirs(metaRoot);
    await removeEmptyYearDirs(webRoot);
  }

  // Other photos (portrait, studio): public/photos/<name>/
  const photosRoot = path.join(siteDir, 'public/photos');
  for (const photo of photos.photos) {
    if (only.length && !only.includes(photo.name)) continue;
    const dir = path.join(photosRoot, photo.name);
    const master = await fs.readFile(photo.masterPath);
    const fingerprint = sha1(String(PIPELINE_VERSION), master, JSON.stringify(photo.data));
    if ((await readJson(path.join(dir, 'info.json')))?.fingerprint === fingerprint && !force) { skipped++; continue; }
    log(`→ fotky/${photo.name}`);
    const m = await loadMaster(master);
    await fs.rm(dir, { recursive: true, force: true });
    await fs.mkdir(dir, { recursive: true });
    const widths = await responsive(m.buf, m.width, dir, '', img.photos.widths, img.web.quality);
    const info = { width: m.width, height: m.height, widths, dominant: await dominantColor(m.buf), alt: photo.data.alt ?? '', caption: photo.data.caption ?? '', fingerprint };
    await fs.writeFile(path.join(dir, 'info.json'), JSON.stringify(info, null, 2));
    processed++;
  }
  if (!only.length && (await exists(photosRoot))) {
    const wanted = new Set(photos.photos.map((p) => p.name));
    for (const e of await fs.readdir(photosRoot, { withFileTypes: true })) {
      if (e.isDirectory() && !wanted.has(e.name)) {
        await fs.rm(path.join(photosRoot, e.name), { recursive: true });
        pruned.push(`public/photos/${e.name}/`);
      }
    }
    if ((await fs.readdir(photosRoot)).length === 0) await fs.rmdir(photosRoot);
  }
  pruned.forEach((p) => log(`- removed ${p}`));

  return { ok: missing.length === 0, problems: [], created, assigned, processed, skipped, missing, pruned };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const args = process.argv.slice(2);
  // On GitHub Actions the result is also written to the run page.
  const summary = (r, e) => process.env.GITHUB_STEP_SUMMARY && fs.appendFile(process.env.GITHUB_STEP_SUMMARY, formatSummary(r, e));
  try {
    const r = await run({ force: args.includes('--force'), only: args.filter((a) => !a.startsWith('--')) });
    r.problems.forEach((p) => console.error(`✗ ${p}`));
    if (r.problems.length === 0) console.log(`Done: ${r.processed} processed, ${r.skipped} unchanged.`);
    if (r.missing.length) console.error(`Missing master photo for: ${r.missing.join(', ')}`);
    await summary(r);
    if (!r.ok) process.exitCode = 1;
  } catch (e) {
    console.error(`✗ ${e.message}`);
    await summary(null, e);
    process.exitCode = 1;
  }
}
